### ISSUE TITLE
Investigate potential go routine leak for testutil.NewBucketStore

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#234]
(Test more before putting issue on https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/storage package)

Reason:

<details><summary>This does not leak</summary>

```go
func NewObjectStoreBucket(t testing.TB) (*gcs.Bucket, func(), error) {
	_, ok := os.LookupEnv("GCP_PROJECT")
	// TODO(fabxc): make it run against a mock store if no actual bucket is configured.
	if !ok {
		t.Skip("test can only run against a defined GCP_PROJECT")
	}

	ctx, cancel := context.WithCancel(context.Background())
	gcsClient, err := storage.NewClient(ctx)
	if err != nil {
		cancel()
		return nil, nil, err
	}
	src := rand.NewSource(time.Now().UnixNano())
	name := fmt.Sprintf("test_%s_%x", strings.ToLower(t.Name()), src.Int63())
	fmt.Println(name)
	bkt := gcsClient.Bucket(name)
	//err = bkt.Create(ctx, project, nil)
	//if err != nil {
	//	cancel()
	//	gcsClient.Close()
	//	return nil, nil, err
	//}

	return gcs.NewBucket(name, bkt, nil), func() {
		//deleteAllBucket(t, ctx, bkt)
		cancel()
		gcsClient.Close()
	}, nil
}

func deleteAllBucket(t testing.TB, ctx context.Context, bkt *storage.BucketHandle) {
	var wg sync.WaitGroup

	objs := bkt.Objects(ctx, nil)
	for {
		oi, err := objs.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			t.Logf("iterating over bucket objects failed: %s", err)
			wg.Wait()
			return
		}

		wg.Add(1)
		go func() {
			if err := bkt.Object(oi.Name).Delete(ctx); err != nil {
				t.Logf("deleting object %s failed: %s", oi.Name, err)
			}
			wg.Done()
		}()
	}
	wg.Wait()

	err := bkt.Delete(ctx)
	if err != nil {
		t.Logf("deleting bucket failed: %s", err)
	}
}
```
</details>

However, un-commenting either `bkt.Create` or `deleteAllBucket` or both leads to leaks:
<details><summary>Leaktest</summary>

```
	leaktest.go:90: leaktest: timed out checking goroutines
	leaktest.go:108: leaktest: leaked goroutine: goroutine 11 [IO wait]:
		internal/poll.runtime_pollWait(0x7f916088fe60, 0x72, 0xc42005d858)
			/usr/local/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc4200dea18, 0x72, 0xffffffffffffff00, 0xa8d460, 0xd3c710)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
		internal/poll.(*pollDesc).waitRead(0xc4200dea18, 0xc4206c3000, 0x1000, 0x1000)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
		internal/poll.(*FD).Read(0xc4200dea00, 0xc4206c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
		net.(*netFD).Read(0xc4200dea00, 0xc4206c3000, 0x1000, 0x1000, 0x435c09, 0xc42019f500, 0x200000003)
			/usr/local/go/src/net/fd_unix.go:202 +0x4f
		net.(*conn).Read(0xc4201ba028, 0xc4206c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:176 +0x6a
		crypto/tls.(*block).readFromUntil(0xc4206c4570, 0x7f9160894268, 0xc4201ba028, 0x5, 0xc4201ba028, 0xc42005da10)
			/usr/local/go/src/crypto/tls/conn.go:493 +0x96
		crypto/tls.(*Conn).readRecord(0xc4200ba380, 0xa49217, 0xc4200ba4a0, 0xc42019f500)
			/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
		crypto/tls.(*Conn).Read(0xc4200ba380, 0xc4200fd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
		bufio.(*Reader).Read(0xc420198360, 0xc42067a818, 0x9, 0x9, 0xc4200ba6b0, 0x67a960, 0xc4200ba6b0)
			/usr/local/go/src/bufio/bufio.go:216 +0x238
		io.ReadAtLeast(0xa8b460, 0xc420198360, 0xc42067a818, 0x9, 0x9, 0x9, 0x6e5271, 0xc4200ba380, 0xc4200fc000)
			/usr/local/go/src/io/io.go:309 +0x86
		io.ReadFull(0xa8b460, 0xc420198360, 0xc42067a818, 0x9, 0x9, 0x72bab4, 0x7f91607fd8b0, 0xc4200ba380)
			/usr/local/go/src/io/io.go:327 +0x58
		net/http.http2readFrameHeader(0xc42067a818, 0x9, 0x9, 0xa8b460, 0xc420198360, 0x0, 0xc400000000, 0x42c1e4, 0xa49288)
			/usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
		net/http.(*http2Framer).ReadFrame(0xc42067a7e0, 0xc42068f620, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
		net/http.(*http2clientConnReadLoop).run(0xc42005dfb8, 0xa48b78, 0xc42027cfb8)
			/usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
		net/http.(*http2ClientConn).readLoop(0xc42014fc00)
			/usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
		created by net/http.(*http2Transport).newClientConn
			/usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c
	leaktest.go:108: leaktest: leaked goroutine: goroutine 6 [IO wait]:
		internal/poll.runtime_pollWait(0x7f916088ff30, 0x72, 0xc420496858)
			/usr/local/go/src/runtime/netpoll.go:173 +0x57
		internal/poll.(*pollDesc).wait(0xc4200dea98, 0x72, 0xffffffffffffff00, 0xa8d460, 0xd3c710)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
		internal/poll.(*pollDesc).waitRead(0xc4200dea98, 0xc4204ac400, 0x400, 0x400)
			/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
		internal/poll.(*FD).Read(0xc4200dea80, 0xc4204ac400, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
		net.(*netFD).Read(0xc4200dea80, 0xc4204ac400, 0x400, 0x400, 0x435c09, 0xc420085b00, 0x200000003)
			/usr/local/go/src/net/fd_unix.go:202 +0x4f
		net.(*conn).Read(0xc4201ba010, 0xc4204ac400, 0x400, 0x400, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/net.go:176 +0x6a
		crypto/tls.(*block).readFromUntil(0xc42009f2f0, 0x7f9160894268, 0xc4201ba010, 0x5, 0xc4201ba010, 0xc420496a10)
			/usr/local/go/src/crypto/tls/conn.go:493 +0x96
		crypto/tls.(*Conn).readRecord(0xc4204a8000, 0xa49217, 0xc4204a8120, 0xc420085b00)
			/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
		crypto/tls.(*Conn).Read(0xc4204a8000, 0xc4206bd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
			/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
		bufio.(*Reader).Read(0xc420199e00, 0xc4203e1298, 0x9, 0x9, 0xc4204a8330, 0x67a960, 0xc4204a8330)
			/usr/local/go/src/bufio/bufio.go:216 +0x238
		io.ReadAtLeast(0xa8b460, 0xc420199e00, 0xc4203e1298, 0x9, 0x9, 0x9, 0x6e5271, 0xc4204a8000, 0xc4206bc000)
			/usr/local/go/src/io/io.go:309 +0x86
		io.ReadFull(0xa8b460, 0xc420199e00, 0xc4203e1298, 0x9, 0x9, 0x72bab4, 0x7f91607fd8b0, 0xc4204a8000)
			/usr/local/go/src/io/io.go:327 +0x58
		net/http.http2readFrameHeader(0xc4203e1298, 0x9, 0x9, 0xa8b460, 0xc420199e00, 0x0, 0xc400000000, 0x42c1e4, 0xa49288)
			/usr/local/go/src/net/http/h2_bundle.go:1517 +0x7b
		net/http.(*http2Framer).ReadFrame(0xc4203e1260, 0xc4206c8000, 0x0, 0x0, 0x0)
			/usr/local/go/src/net/http/h2_bundle.go:1775 +0xa4
		net/http.(*http2clientConnReadLoop).run(0xc420496fb8, 0xa48b78, 0xc42027dfb8)
			/usr/local/go/src/net/http/h2_bundle.go:8028 +0x90
		net/http.(*http2ClientConn).readLoop(0xc42014e700)
			/usr/local/go/src/net/http/h2_bundle.go:7956 +0x68
		created by net/http.(*http2Transport).newClientConn
			/usr/local/go/src/net/http/h2_bundle.go:7143 +0x65c

```
</details>

**Comment by Bplotka** [comment]
This should not cause real troubles for production setups, because we are not creating/removing GCS clients dynamically. But still sounds bad. (:

**Comment by Bplotka** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1025

**Comment by daixiang0** [comment]
@bwplotka seems we have figured out it?

**Comment by bwplotka** [comment]
Kind of. We stopped using leaktest instead of using parallel.
