### ISSUE TITLE
Compactor is panicing

### ISSUE THREAD

**Issue by homelessnessbo** [thanos-io/thanos#2975]
Thanos compactor v0.14.0

**Object Storage Provider**:

GCS

**What happened**:

Compactor is continiously panicing time after time

**How to reproduce it (as minimally and precisely as possible)**:

I don't know yet, but ready to provide needed data 

**Full logs to relevant components**:

<details>Logs
<p>

```
 
"panic: assignment to entry in nil map
goroutine 276 [running]:
github.com/thanos-io/thanos/pkg/block.(*ReplicaLabelRemover).Modify(0xc000c4e810, 0x266a460, 0xc00054bf00, 0xc003a58180, 0xc000274a00, 0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:696 +0x3bc
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch(0xc000902660, 0x266a460, 0xc00054bf00, 0xc00054bc00, 0xc00054bbc0, 0x4, 0x4, 0xc00011c8d0, 0x1, 0x1, ...)
	/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:440 +0x626
github.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch(0xc000902ae0, 0x266a460, 0xc00054bf00, 0xc, 0x0, 0x0, 0x2)
	/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:473 +0x9f
github.com/thanos-io/thanos/pkg/compact.(*Syncer).SyncMetas(0xc000bab680, 0x266a460, 0xc00054bf00, 0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/compact/compact.go:126 +0x9e
github.com/thanos-io/thanos/pkg/compact.(*BucketCompactor).Compact(0xc000903260, 0x266a460, 0xc00054bf00, 0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/compact/compact.go:944 +0x2c2
main.runCompact.func5(0xc00011e010, 0x1)
	/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:294 +0x15a
main.runCompact.func6.1(0x45d964b800, 0xc0000de0a0)
	/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:348 +0x99
github.com/thanos-io/thanos/pkg/runutil.Repeat(0x45d964b800, 0xc000056780, 0xc000dbfee0, 0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:72 +0x8e
main.runCompact.func6(0x0, 0x0)
	/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:347 +0x29e
github.com/oklog/run.(*Group).Run.func1(0xc0005a24e0, 0xc000bab700, 0xc00011cfb0)
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0xbb
```

</p>
</details>

**Anything else we need to know**:
previous line in logs is:
```
 "level=warn ts=2020-08-04T10:05:30.154615689Z caller=fetcher.go:695 msg="block has no labels left, creating one" prometheus_replica=deduped
"
```

**Comment by bwplotka** [comment]
Thanks for this. It was fixed on master already and we decided to push fix on 0.15.0, but happy to consider 0.14.1 if neeed.

https://github.com/thanos-io/thanos/blob/master/CHANGELOG.md#fixed
