### ISSUE TITLE
Add goleak VerifyTestMain to objstore/objtesting package

### ISSUE THREAD

**Issue by mneverov** [thanos-io/thanos#3041]
While working on #3023 it was discovered that tests with cloud storages have goroutine leaks.
Please add goleak VerifyTestMain after fixing the root cause.
For more context see the [discussion](https://github.com/thanos-io/thanos/pull/3029).

Log from the pipeline:
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 25 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 25 [select]:
net/http.(*persistConn).writeLoop(0xc000392900)
	/usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0xc7b

 Goroutine 24 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7fec8d54dee8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000398618, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000398600, 0xc00038f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000398600, 0xc00038f000, 0x1000, 0x1000, 0x43930c, 0xc00006bb70, 0x465740)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010b40, 0xc00038f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc000392900, 0xc00038f000, 0x1000, 0x1000, 0xc000041500, 0xc00006bc70, 0x406ca5)
	/usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc00034bda0)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc00034bda0, 0x1, 0x0, 0x0, 0x1, 0xc00044e000, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000392900)
	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0xc56

 Goroutine 31 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 31 [IO wait]:
internal/poll.runtime_pollWait(0x7fec8d54de08, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000425398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000425380, 0xc0003d3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000425380, 0xc0003d3000, 0x1000, 0x1000, 0xc00034a9c0, 0xc000064da8, 0xc000064c38)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000110a8, 0xc0003d3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc000429c20, 0xc0003d3000, 0x1000, 0x1000, 0xc000064eb0, 0x466030, 0xc000064eb0)
	/usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc000432b40)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000432b40, 0x1, 0x2, 0x0, 0x0, 0xc00044e700, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000429c20)
	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0xc56

 Goroutine 32 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 32 [select]:
net/http.(*persistConn).writeLoop(0xc000429c20)
	/usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0xc7b
]
FAIL	github.com/thanos-io/thanos/pkg/objstore/objtesting	0.929s
```

**Comment by bwplotka** [comment]
Still valid. help wanted (:

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗
