### ISSUE TITLE
Add goleak VerifyTestMain to store package

### ISSUE THREAD

**Issue by mneverov** [thanos-io/thanos#3042]
While working on #3023 it was discovered that tests with cloud storages have goroutine leaks.
Please add goleak VerifyTestMain after fixing the root cause.
For more context see the [discussion](https://github.com/thanos-io/thanos/pull/3029).

Log from the pipeline:
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 7291 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 7291 [select]:
net/http.(*persistConn).writeLoop(0xc000e8ab40)
	/usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0xc7b

 Goroutine 7314 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 7314 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd8ca4d038, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc001006a98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001006a80, 0xc00100b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001006a80, 0xc00100b000, 0x1000, 0x1000, 0x43930c, 0xc0006cbb70, 0x465cb0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010230, 0xc00100b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc001002d80, 0xc00100b000, 0x1000, 0x1000, 0xc000f39260, 0xc0006cbc70, 0x406ca5)
	/usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc00100c840)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc00100c840, 0x1, 0x0, 0x0, 0x1, 0xc001030a00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc001002d80)
	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0xc56

 Goroutine 7290 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 7290 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd8ca4d8f8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000e25298, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000e25280, 0xc000ecd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000e25280, 0xc000ecd000, 0x1000, 0x1000, 0xc012c7b3e0, 0xc000eeada8, 0xc000eeac38)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc001fb1e30, 0xc000ecd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc000e8ab40, 0xc000ecd000, 0x1000, 0x1000, 0xc000eeaeb0, 0x4665a0, 0xc000eeaeb0)
	/usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc000e86e40)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000e86e40, 0x1, 0x2, 0x0, 0x0, 0xc001058500, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000e8ab40)
	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0xc56

 Goroutine 7315 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 7315 [select]:
net/http.(*persistConn).writeLoop(0xc001002d80)
	/usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0xc7b
]
FAIL	github.com/thanos-io/thanos/pkg/store	123.272s
```

**Comment by bwplotka** [comment]
Yup, still valid (:

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗
