### ISSUE TITLE
query Frontend : panic: runtime error: index out of range [8] with length 8

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3536]
Thanos 0.17.1

I don't have any more information that I can provide (on what I'm aware of atm). 

```
panic: runtime error: index out of range [8] with length 8

goroutine 2852721 [running]:
github.com/thanos-io/thanos/pkg/store/labelpb.ZLabelSets.Less(0xc006000000, 0x4a31, 0x5000, 0x47b3, 0x47b2, 0xc00606b901)
	/go/src/github.com/thanos-io/thanos/pkg/store/labelpb/label.go:311 +0x2f6
sort.insertionSort(0x1d41720, 0xc0009ba000, 0x47b2, 0x47bc)
	/usr/local/go/src/sort/sort.go:27 +0xc4
sort.quickSort(0x1d41720, 0xc0009ba000, 0x47b2, 0x47bc, 0x13)
	/usr/local/go/src/sort/sort.go:209 +0x205
sort.quickSort(0x1d41720, 0xc0009ba000, 0x46b7, 0x4874, 0x18)
	/usr/local/go/src/sort/sort.go:197 +0x133
sort.quickSort(0x1d41720, 0xc0009ba000, 0x40ec, 0x4a31, 0x1a)
	/usr/local/go/src/sort/sort.go:197 +0x133
sort.quickSort(0x1d41720, 0xc0009ba000, 0x37a6, 0x4a31, 0x1b)
	/usr/local/go/src/sort/sort.go:197 +0x133
sort.quickSort(0x1d41720, 0xc0009ba000, 0x2519, 0x4a31, 0x1c)
	/usr/local/go/src/sort/sort.go:197 +0x133
sort.quickSort(0x1d41720, 0xc0009ba000, 0x0, 0x4a31, 0x1d)
	/usr/local/go/src/sort/sort.go:197 +0x133
sort.Sort(0x1d41720, 0xc0009ba000)
	/usr/local/go/src/sort/sort.go:218 +0x7a
github.com/thanos-io/thanos/pkg/queryfrontend.labelsCodec.MergeResponse(0x1d4d960, 0x2a4ce20, 0x18d0400, 0x4e94914f0000, 0xc00453a020, 0x2, 0x2, 0x20, 0x17ecf60, 0x1d3dd01, ...)
	/go/src/github.com/thanos-io/thanos/pkg/queryfrontend/labels_codec.go:103 +0x1a5
github.com/cortexproject/cortex/pkg/querier/queryrange.resultsCache.handleHit(0x1d13820, 0xc0009bd7a0, 0x0, 0x0, 0x14, 0x2710, 0x4e94914f0000, 0x0, 0x64, 0x0, ...)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/results_cache.go:354 +0x948
github.com/cortexproject/cortex/pkg/querier/queryrange.resultsCache.Do(0x1d13820, 0xc0009bd7a0, 0x0, 0x0, 0x14, 0x2710, 0x4e94914f0000, 0x0, 0x64, 0x0, ...)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/results_cache.go:209 +0x310
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x1d479a0, 0xc000abc1e0, 0xd, 0xbfea4a57d04e0529)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/instrumentation.go:28 +0x62
github.com/weaveworks/common/instrument.CollectedRequest(0x1d478e0, 0xc00119df80, 0x1af87ff, 0xd, 0x1d3efa0, 0xc00020ebf8, 0x1b7c978, 0xc0007ace78, 0x40170e, 0x2)
	/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20200914083218-61ffdd448099/instrument/instrument.go:152 +0x271
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1(0x1d478e0, 0xc00119df80, 0x1d66140, 0xc00126b100, 0xc000561e60, 0xc0007ebf60, 0x1, 0x101)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/instrumentation.go:26 +0xe9
github.com/cortexproject/cortex/pkg/querier/queryrange.HandlerFunc.Do(0xc000889e80, 0x1d478e0, 0xc00119df80, 0x1d66140, 0xc00126b100, 0xc0007ebf70, 0x406305, 0xc000561c78, 0x0)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/roundtrip.go:96 +0x4e
github.com/cortexproject/cortex/pkg/querier/queryrange.DoRequests.func2(0xc000561e60, 0x1d17b20, 0xc000889e80, 0xc0006c6a90, 0xc000561f20, 0xc000561ec0)
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/util.go:45 +0xbc
created by github.com/cortexproject/cortex/pkg/querier/queryrange.DoRequests
	/go/pkg/mod/github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076/pkg/querier/queryrange/util.go:43 +0x2de
```

**Comment by arvidsnet** [comment]
looks like duplicate of https://github.com/thanos-io/thanos/issues/3515

**Comment by wiardvanrij** [comment]
Closing as duplicate of #3515
