### ISSUE TITLE
query msg="runtime panic in parser" err="runtime error: slice bounds out of range [2:1]"

### ISSUE THREAD

**Issue by cuiyuanrong** [thanos-io/thanos#3642]
Thanos, Prometheus and Golang version used:

prometheus/prometheus:v2.20.1
thanos/thanos:v0.17.2

What happened:

When running a query with a 3 hours timespan, runtime panic in parser.

Full logs to relevant components:
```
level=debug ts=2020-12-18T09:44:02.546660766Z caller=main.go:64 msg="maxprocs: Updating GOMAXPROCS=[4]: determined from CPU quota" 
level=info ts=2020-12-18T09:44:02.547076306Z caller=main.go:98 msg="Tracing will be disabled" 
level=debug ts=2020-12-18T09:44:02.548257982Z caller=engine.go:283 msg="Lookback delta is zero, setting to default value" value=5m0s 
level=info ts=2020-12-18T09:44:02.549935069Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable" 
level=info ts=2020-12-18T09:44:02.550378425Z caller=query.go:506 msg="starting query node" 
level=debug ts=2020-12-18T09:44:02.550609659Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=0 
level=info ts=2020-12-18T09:44:02.550644377Z caller=intrumentation.go:48 msg="changing probe status" status=ready 
level=debug ts=2020-12-18T09:44:02.550743322Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=0 cachedStores=0 
level=info ts=2020-12-18T09:44:02.55081199Z caller=intrumentation.go:60 msg="changing probe status" status=healthy 
level=info ts=2020-12-18T09:44:02.550830774Z caller=http.go:58 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:9090 
level=info ts=2020-12-18T09:44:02.551079674Z caller=grpc.go:116 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901 
level=debug ts=2020-12-18T09:44:07.550744852Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=0 
level=debug ts=2020-12-18T09:44:07.555110987Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=0 
level=info ts=2020-12-18T09:44:07.555220428Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=10.21.16.24:30002 extLset="{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"}" 
level=info ts=2020-12-18T09:44:07.555265822Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=192.168.151.29:10901 extLset="{ruler_replica=\"thanos-ruler-0\"}" 
level=info ts=2020-12-18T09:44:07.555304042Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=192.168.109.160:10901 extLset="{monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-0\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"}" 
level=info ts=2020-12-18T09:44:07.555348163Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=10.21.16.87:8001 extLset="{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"}" 
level=info ts=2020-12-18T09:44:07.555361716Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=10.21.16.249:30002 extLset="{monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"}" 
level=info ts=2020-12-18T09:44:07.555427538Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=192.168.61.163:10901 extLset="{replica=\"thanos-receive-0\", receive=\"true\", tenant_id=\"default-tenant\"}" 
level=debug ts=2020-12-18T09:44:12.550825953Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:12.552897026Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:17.550784803Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:17.553006404Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:22.55075245Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:22.552857854Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:27.550729866Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:27.552811204Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:32.550650294Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:32.552894586Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:37.550756024Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6 
level=debug ts=2020-12-18T09:44:37.553250711Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6 
level=debug ts=2020-12-18T09:44:38.009107441Z caller=proxy.go:283 msg="Store Addr: 192.168.109.160:10901 LabelSets: {monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-0\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"} Mint: 1599565193313 Maxt: 1608278400000 queried;Store Addr: 10.21.16.87:8001 LabelSets: {monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 10.21.16.249:30002 LabelSets: {monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 192.168.61.163:10901 LabelSets: {replica=\"thanos-receive-0\", receive=\"true\", tenant_id=\"default-tenant\"} Mint: 0 Maxt: 9223372036854775807 queried;Store Addr: 10.21.16.24:30002 LabelSets: {monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 192.168.151.29:10901 LabelSets: {ruler_replica=\"thanos-ruler-0\"} Mint: 0 Maxt: 9223372036854775807 queried" 
level=debug ts=2020-12-18T09:44:38.0094082Z caller=proxy.go:283 msg="Store Addr: 10.21.16.24:30002 LabelSets: {monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 192.168.151.29:10901 LabelSets: {ruler_replica=\"thanos-ruler-0\"} Mint: 0 Maxt: 9223372036854775807 queried;Store Addr: 192.168.109.160:10901 LabelSets: {monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"},{monitor_cluster_name=\"prod-bj\", monitor_env_name=\"prod\", replica=\"prometheus-1\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-0\"},{monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"} Mint: 1599565193313 Maxt: 1608278400000 queried;Store Addr: 10.21.16.87:8001 LabelSets: {monitor_cluster_name=\"test\", monitor_env_name=\"test\", replica=\"prometheus-1\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 10.21.16.249:30002 LabelSets: {monitor_cluster_name=\"infra-bj\", monitor_env_name=\"prod\", replica=\"prometheus-0\"} Mint: 1608012000000 Maxt: 9223372036854775807 queried;Store Addr: 192.168.61.163:10901 LabelSets: {replica=\"thanos-receive-0\", receive=\"true\", tenant_id=\"default-tenant\"} Mint: 0 Maxt: 9223372036854775807 queried"

level=error ts=2020-12-18T09:44:38.163094555Z caller=engine.go:775 msg="runtime panic in parser" err="runtime error: slice bounds out of range [2:1]" stacktrace="goroutine 629 [running]:\ngithub.com/prometheus/prometheus/promql.(*evaluator).recover(0xc0008f0a18, 0xc0008f0850, 0xc0008f0868)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:773 +0x31e\npanic(0x19d5b40, 0xc000a220c0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x175\ngithub.com/prometheus/prometheus/tsdb/chunkenc.(*XORChunk).iterator(0xc000e27120, 0x0, 0x0, 0xc000e27120)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/tsdb/chunkenc/xor.go:128 +0x2af\ngithub.com/prometheus/prometheus/tsdb/chunkenc.(*XORChunk).Iterator(0xc000e27120, 0x0, 0x0, 0x7f791c8fde98, 0x0)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/tsdb/chunkenc/xor.go:136 +0x3f\ngithub.com/thanos-io/thanos/pkg/query.getFirstIterator(0xc0008edf20, 0x2, 0x2, 0xc000e0d360, 0xc000a13dc0)\n\t/go/src/github.com/thanos-io/thanos/pkg/query/iter.go:227 +0x131\ngithub.com/thanos-io/thanos/pkg/query.(*chunkSeries).Iterator(0xc000e24e40, 0xc0008ee2b0, 0x11a33de)\n\t/go/src/github.com/thanos-io/thanos/pkg/query/iter.go:186 +0xfc9\ngithub.com/thanos-io/thanos/pkg/query.(*dedupSeries).Iterator(0xc0004def40, 0x3a98, 0x1)\n\t/go/src/github.com/thanos-io/thanos/pkg/query/iter.go:466 +0x5a\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0008f0a18, 0x1d46e80, 0xc00089dcb0, 0xc0004b9a10, 0x1, 0x0, 0x18, 0x0)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:1110 +0x1c79\ngithub.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc0008f0a18, 0xc0008ef5a0, 0xc0008ef6d0, 0x2, 0x2, 0x0, 0xc, 0xc, 0x0, 0x0, ...)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:866 +0x164d\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0008f0a18, 0x1d46e00, 0xc0008a8240, 0xc000810240, 0xc, 0xc, 0x0, 0x0)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:1015 +0x7bf\ngithub.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc0008f0a18, 0xc0008f03d8, 0xc0008f04a8, 0x2, 0x2, 0x0, 0x7400000200, 0x17ded40, 0x1, 0x2e, ...)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:866 +0x164d\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval(0xc000a3aa18, 0x1d46e40, 0xc00088d880, 0x1d46a00, 0xc0008e8210, 0xf, 0x4, 0x1afadbc)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:1247 +0x369d\ngithub.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc000a3aa18, 0x1d46e40, 0xc00088d880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:788 +0xb2\ngithub.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc000a12700, 0x1d46a00, 0xc00089de60, 0xc0008a82a0, 0xc00089ae10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:555 +0xd0a\ngithub.com/prometheus/prometheus/promql.(*Engine).exec(0xc000a12700, 0x1d46a00, 0xc00089de60, 0xc0008a82a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:461 +0x511\ngithub.com/prometheus/prometheus/promql.(*query).Exec(0xc0008a82a0, 0x1d46a00, 0xc00089da10, 0x13)\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201029103703-63be30dceed9/promql/engine.go:173 +0x9d\ngithub.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).queryRange(0xc000125480, 0xc00089f000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/thanos-io/thanos/pkg/api/query/v1.go:402 +0xc82\ngithub.com/thanos-io/thanos/pkg/api.GetInstr.func1.1(0x1d39040, 0xc0000f3f80, 0xc00089f000)\n\t/go/src/github.com/thanos-io/thanos/pkg/api/api.go:206 +0x58\nnet/http.HandlerFunc.ServeHTTP(0xc000478d00, 0x1d39040, 0xc0000f3f80, 0xc00089f000)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1(0x1d39040, 0xc0000f3f80, 0xc00089ef00)\n\t/go/src/github.com/thanos-io/thanos/pkg/server/http/middleware/request_id.go:40 +0x20a\nnet/http.HandlerFunc.ServeHTTP(0xc000317420, 0x1d39040, 0xc0000f3f80, 0xc00089ef00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1d3d100, 0xc000814fe0, 0xc00089ef00)\n\t/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x28f\nnet/http.HandlerFunc.ServeHTTP(0xc000abd650, 0x1d3d100, 0xc000814fe0, 0xc00089ef00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1(0x1d3d100, 0xc000814fe0, 0xc00089ee00)\n\t/go/src/github.com/thanos-io/thanos/pkg/tracing/http.go:46 +0x553\nnet/http.HandlerFunc.ServeHTTP(0xc0000cc5a0, 0x1d3d100, 0xc000814fe0, 0xc00089ee00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1(0x7f78f58caae8, 0xc00089ad20, 0xc00089ee00)\n\t/go/src/github.com/thanos-io/thanos/pkg/logging/http.go:53 +0x205\nnet/http.HandlerFunc.ServeHTTP(0xc000abd680, 0x7f78f58caae8, 0xc00089ad20, 0xc00089ee00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f78f58caae8, 0xc00089acd0, 0xc00089ee00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:196 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xc000abd9b0, 0x7f78f58caae8, 0xc00089acd0, 0xc00089ee00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x7f78f58caae8, 0xc00089ac80, 0xc00089ee00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:100 +0xda\nnet/http.HandlerFunc.ServeHTTP(0xc000abdbf0, 0x7f78f58caae8, 0xc00089ac80, 0xc00089ee00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1(0x7f78f58caae8, 0xc00089ac30, 0xc00089ee00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:163 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xc000abde60, 0x7f78f58caae8, 0xc00089ac30, 0xc00089ee00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1(0x1d3f600, 0xc000515ea0, 0xc00089ee00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:68 +0x11c\ngithub.com/prometheus/common/route.(*Router).handle.func1(0x1d3f600, 0xc000515ea0, 0xc00089ec00, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/prometheus/common@v0.14.0/route/route.go:83 +0x283\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0007016e0, 0x1d3f600, 0xc000515ea0, 0xc00089ec00)\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc00080c360, 0x1d3f600, 0xc000515ea0, 0xc00089ec00)\n\t/go/pkg/mod/github.com/prometheus/common@v0.14.0/route/route.go:121 +0x4c\nnet/http.(*ServeMux).ServeHTTP(0xc000a2db80, 0x1d3f600, 0xc000515ea0, 0xc00089ec00)\n\t/usr/local/go/src/net/http/server.go:2417 +0x1ad\nnet/http.serverHandler.ServeHTTP(0xc0002a4000, 0x1d3f600, 0xc000515ea0, 0xc00089ec00)\n\t/usr/local/go/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc000229f40, 0x1d46940, 0xc00088d4c0)\n\t/usr/local/go/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2969 +0x36c\n"
```

**Comment by GiedriusS** [comment]
@cuiyuanrong could you please paste the query or add some steps on how we could reproduce this?

**Comment by cuiyuanrong** [comment]
Promql : sum(increase(uri_latency_sum{method="router", endpoint=~"/api/collection|/user/getrecord"}[2m] offset 2d))/sum(increase(uri_latency_count{method="router", endpoint=~"/api/collection|/user/getrecord"}[2m] offset 2d))

pometheus is normal.

thanos is the exception.
