### ISSUE TITLE
Thanos store - fatal error: invalid runtime symbol table

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3803]
Thanos 17.2

Store component

Following trace received: 
```
runtime: invalid pc-encoded table f=github.com/modern-go/reflect2.(*UnsafeIFaceType).Comparable pc=0xec892a targetpc=0xec892d tab=[0/0]0x0
	value=0 until pc=0xec88d3
	value=24 until pc=0xec890e
	value=0 until pc=0xec8916
	value=24 until pc=0xec892a
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigreturn called from 0x7
stack: frame={sp:0xc013ff3380, fp:0xc013ff3388} stack=[0xc013fec000,0xc013ff4000)
000000c013ff3280:  0000000000000000  0000000000000000
000000c013ff3290:  000000c013ff34b0  000000c013ff3380
000000c013ff32a0:  000000c013ff3318  000000000044ce85 <runtime.sigtrampgo+421>
000000c013ff32b0:  000000c00000001b  000000c013ff34b0
000000c013ff32c0:  000000c013ff3380  000000c011bcfb00
000000c013ff32d0:  0000000000000000  0000000000000000
000000c013ff32e0:  0000000000000000  0000000000000000
000000c013ff32f0:  0000000000000000  0000000000000000
000000c013ff3300:  000000c011bcfb00  000000c013ff34b0
000000c013ff3310:  000000c013ff3380  000000c013ff3370
000000c013ff3320:  0000000000471a23 <runtime.sigtramp+67>  000000000000001b
000000c013ff3330:  000000c013ff34b0  000000c013ff3380
000000c013ff3340:  00000000fe7a8e12  00000000a8bb1dd8
000000c013ff3350:  00000000fb7e7da0  000000c01f3dfcc0
000000c013ff3360:  000000c013ff3370  00000000ab9393e3
000000c013ff3370:  000000c0245317c0  0000000000471b20 <runtime.sigreturn+0>
000000c013ff3380: <0000000000000007 >0000000000000000
000000c013ff3390:  000000c013fec000  0000000000000000
000000c013ff33a0:  0000000000008000  00000000732edcfc
000000c013ff33b0:  00000000e4cb0c13  00000000ca0c66a8
000000c013ff33c0:  000000007e8b9de2  000000c01f3dfcc0
000000c013ff33d0:  00000000fb7e7da0  00000000a8bb1dd8
000000c013ff33e0:  00000000fe7a8e12  000000c024531c50
000000c013ff33f0:  000000c01f3dfcc0  000000c0245317c0
000000c013ff3400:  00000000ab9393e3  000000001675c9ae
000000c013ff3410:  00000000f96e769d  000000009212cfec
000000c013ff3420:  000000c0245319c0  0000000000f2c699 <github.com/minio/sha256-simd.blockAvx2+249>
000000c013ff3430:  0000000000000287  002b000000000033
000000c013ff3440:  0000000000000000  0000000000000000
000000c013ff3450:  0000000000000000  0000000000000000
000000c013ff3460:  000000c013ff3540  0000000000000000
000000c013ff3470:  0000000000000000  0000000000000000
000000c013ff3480:  0000000000000000
runtime.throw(0x1b14a03, 0x1c)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.pcvalue(0x23c1470, 0x27f1140, 0x25dd3c, 0xec892d, 0xc013ff2da8, 0x2422501, 0x448, 0xf2c5c2)
	/usr/local/go/src/runtime/symtab.go:813 +0x59f
runtime.funcspdelta(0x23c1470, 0x27f1140, 0xec892d, 0xc013ff2da8, 0xc000000448)
	/usr/local/go/src/runtime/symtab.go:867 +0x65
runtime.gentraceback(0xf2c699, 0xc0245319c0, 0x0, 0xc011bcfb00, 0x0, 0xc013ff3000, 0x40, 0x0, 0x0, 0x6, ...)
	/usr/local/go/src/runtime/traceback.go:220 +0x1665
runtime.sigprof(0xf2c699, 0xc0245319c0, 0x0, 0xc011bcfb00, 0xc0136bfc00)
	/usr/local/go/src/runtime/proc.go:4041 +0x42c
runtime.sighandler(0xc00000001b, 0xc013ff34b0, 0xc013ff3380, 0xc011bcfb00)
	/usr/local/go/src/runtime/signal_unix.go:527 +0x948
runtime.sigtrampgo(0x1b, 0xc013ff34b0, 0xc013ff3380)
	/usr/local/go/src/runtime/signal_unix.go:449 +0x1a5
runtime.sigtramp(0x7, 0x0, 0xc013fec000, 0x0, 0x8000, 0x732edcfc, 0xe4cb0c13, 0xca0c66a8, 0x7e8b9de2, 0xc01f3dfcc0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:409 +0x43
runtime: unexpected return pc for runtime.sigreturn called from 0x7
stack: frame={sp:0xc013ff3380, fp:0xc013ff3388} stack=[0xc013fec000,0xc013ff4000)
000000c013ff3280:  0000000000000000  0000000000000000
000000c013ff3290:  000000c013ff34b0  000000c013ff3380
000000c013ff32a0:  000000c013ff3318  000000000044ce85 <runtime.sigtrampgo+421>
000000c013ff32b0:  000000c00000001b  000000c013ff34b0
000000c013ff32c0:  000000c013ff3380  000000c011bcfb00
000000c013ff32d0:  0000000000000000  0000000000000000
000000c013ff32e0:  0000000000000000  0000000000000000
000000c013ff32f0:  0000000000000000  0000000000000000
000000c013ff3300:  000000c011bcfb00  000000c013ff34b0
000000c013ff3310:  000000c013ff3380  000000c013ff3370
000000c013ff3320:  0000000000471a23 <runtime.sigtramp+67>  000000000000001b
000000c013ff3330:  000000c013ff34b0  000000c013ff3380
000000c013ff3340:  00000000fe7a8e12  00000000a8bb1dd8
000000c013ff3350:  00000000fb7e7da0  000000c01f3dfcc0
000000c013ff3360:  000000c013ff3370  00000000ab9393e3
000000c013ff3370:  000000c0245317c0  0000000000471b20 <runtime.sigreturn+0>
000000c013ff3380: <0000000000000007 >0000000000000000
000000c013ff3390:  000000c013fec000  0000000000000000
000000c013ff33a0:  0000000000008000  00000000732edcfc
000000c013ff33b0:  00000000e4cb0c13  00000000ca0c66a8
000000c013ff33c0:  000000007e8b9de2  000000c01f3dfcc0
000000c013ff33d0:  00000000fb7e7da0  00000000a8bb1dd8
000000c013ff33e0:  00000000fe7a8e12  000000c024531c50
000000c013ff33f0:  000000c01f3dfcc0  000000c0245317c0
000000c013ff3400:  00000000ab9393e3  000000001675c9ae
000000c013ff3410:  00000000f96e769d  000000009212cfec
000000c013ff3420:  000000c0245319c0  0000000000f2c699 <github.com/minio/sha256-simd.blockAvx2+249>
000000c013ff3430:  0000000000000287  002b000000000033
000000c013ff3440:  0000000000000000  0000000000000000
000000c013ff3450:  0000000000000000  0000000000000000
000000c013ff3460:  000000c013ff3540  0000000000000000
000000c013ff3470:  0000000000000000  0000000000000000
000000c013ff3480:  0000000000000000
runtime.sigreturn(0x0, 0xc013fec000, 0x0, 0x8000, 0x732edcfc, 0xe4cb0c13, 0xca0c66a8, 0x7e8b9de2, 0xc01f3dfcc0, 0xfb7e7da0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:501

goroutine 44690850 [running]:
```

I don't have that much more information. I've been running this version (17.2) since the day it got released and never got this error before. Just wanted to share this.

**Comment by bwplotka** [comment]
sweet (:

**Comment by bwplotka** [comment]
This is weird. What happened when you spot this? Was it restart? It looks weird, like Linux signal from outside caused this. 🤔 Any ideas what could that be? Was it K8s environment?

**Comment by bwplotka** [comment]
Connected but totaly ignored by Go team: https://github.com/golang/go/issues/30092

**Comment by wiardvanrij** [comment]
> This is weird. What happened when you spot this? Was it restart? It looks weird, like Linux signal from outside caused this. 🤔 Any ideas what could that be? Was it K8s environment?

It was indeed on Kubernetes. 
Tbh I tried to fetch more data but I've done some new releases and that kinda ruined my ability to do further debugging. I kinda lost my pointers / examplars ^^ (Our stack is still very much work in progress lol). 

Sorry
