### ISSUE TITLE
query: nil pointer with thanos query api stores during ui reload

### ISSUE THREAD

**Issue by ekristen** [thanos-io/thanos#4371]
**Thanos, Prometheus and Golang version used**:

```
thanos, version 0.20.1 (branch: HEAD, revision: 10023e4882414baa56a8955057f2678f1e724e8c)
  build user:       circleci@22b1af3c9a07
  build date:       20210430-12:46:55
  go version:       go1.16.3
  platform:         linux/amd64
```

**Object Storage Provider**:

S3, but not in use.

**What happened**:

I am frequently hitting a nil pointer in my thanos query instance.

**What you expected to happen**:

I would expect that no nil pointer is hit :)

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure what the problem is exactly, but I'll describe my setup and maybe we can determine the cause.

I am using dnssrvnoa+ service discovery mechanism and it's querying a domain backed by a CoreDNS server. This CoreDNS server is updated with new records where my thanos sidecar instances are at. During dev and testing I'm spinning up and tearing down thanos sidecars and the DNS zone is updating. 

I'm not sure the exact condition but I can definitely make it happen fairly regularly. It appears to generally be around the time a sidecar/store is being removed due to going offline (disappearing from the UI after 5 minutes) and new ones being added in. 

**Full logs to relevant components**:

<details>Logs
<p>

```
2021/06/23 22:04:10 http: panic serving 10.42.8.0:36372: runtime error: invalid memory address or nil pointer dereference
goroutine 200886 [running]:
net/http.(*conn).serve.func1(0xc0001d26e0)
/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1a013a0, 0x2ce7380)
/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).stores(0xc0001ef380, 0xc0000ad900, 0x0, 0x0, 0x0, 0x8000102, 0x0, 0xffffffffffffffff)
/home/circleci/project/pkg/api/query/v1.go:684 +0xcb
github.com/thanos-io/thanos/pkg/api.GetInstr.func1.1(0x1f95050, 0xc000228070, 0xc0000ad900)
/home/circleci/project/pkg/api/api.go:211 +0x42
net/http.HandlerFunc.ServeHTTP(0xc000383fb0, 0x1f95050, 0xc000228070, 0xc0000ad900)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1(0x1f95050, 0xc000228070, 0xc0000ad600)
/home/circleci/project/pkg/server/http/middleware/request_id.go:40 +0x20c
net/http.HandlerFunc.ServeHTTP(0xc000383fc8, 0x1f95050, 0xc000228070, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1f981a0, 0xc0004ae0e0, 0xc0000ad600)
/home/circleci/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x299
net/http.HandlerFunc.ServeHTTP(0xc0004ff7d0, 0x1f981a0, 0xc0004ae0e0, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1(0x1f981a0, 0xc0004ae0e0, 0xc0000ad600)
/home/circleci/project/pkg/logging/http.go:49 +0x2b4
net/http.HandlerFunc.ServeHTTP(0xc0004ff800, 0x1f981a0, 0xc0004ae0e0, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/extprom/http.(*defaultInstrumentationMiddleware).NewHandler.func1(0x7f4df9545760, 0xc000102230, 0xc0000ad600)
/home/circleci/project/pkg/extprom/http/instrument_server.go:108 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc0004ff8c0, 0x7f4df9545760, 0xc000102230, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f4df9545760, 0xc0001021e0, 0xc0000ad600)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:198 +0xee
net/http.HandlerFunc.ServeHTTP(0xc0004ffbc0, 0x7f4df9545760, 0xc0001021e0, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x7f4df9545760, 0xc000102190, 0xc0000ad600)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xdf
net/http.HandlerFunc.ServeHTTP(0xc0004ffe30, 0x7f4df9545760, 0xc000102190, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1(0x1f9a450, 0xc000286000, 0xc0000ad600)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:165 +0xee
net/http.HandlerFunc.ServeHTTP(0xc000604150, 0x1f9a450, 0xc000286000, 0xc0000ad600)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1(0x1f9a450, 0xc000286000, 0xc0000ad400)
/home/circleci/project/pkg/tracing/http.go:46 +0x54c
github.com/prometheus/common/route.(*Router).handle.func1(0x1f9a450, 0xc000286000, 0xc0007a4400, 0x0, 0x0, 0x0)
/home/circleci/go/pkg/mod/github.com/prometheus/common@v0.21.0/route/route.go:83 +0x27f
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000099b60, 0x1f9a450, 0xc000286000, 0xc0007a4400)
/home/circleci/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc000537b80, 0x1f9a450, 0xc000286000, 0xc0007a4400)
/home/circleci/go/pkg/mod/github.com/prometheus/common@v0.21.0/route/route.go:121 +0x4c
net/http.(*ServeMux).ServeHTTP(0xc0002b1840, 0x1f9a450, 0xc000286000, 0xc0007a4400)
/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000486540, 0x1f9a450, 0xc000286000, 0xc0007a4400)
/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001d26e0, 0x1fa1310, 0xc0006ae880)
/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:3013 +0x39b


2021/06/23 22:04:10 http: panic serving 10.42.8.0:36566: runtime error: invalid memory address or nil pointer dereference
goroutine 201137 [running]:
net/http.(*conn).serve.func1(0xc0008aa000)
/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1a013a0, 0x2ce7380)
/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).stores(0xc0001ef380, 0xc00087af00, 0x0, 0x0, 0x0, 0x7000105, 0x0, 0xffffffffffffffff)
/home/circleci/project/pkg/api/query/v1.go:684 +0xcb
github.com/thanos-io/thanos/pkg/api.GetInstr.func1.1(0x1f95050, 0xc000268070, 0xc00087af00)
/home/circleci/project/pkg/api/api.go:211 +0x42
net/http.HandlerFunc.ServeHTTP(0xc000383fb0, 0x1f95050, 0xc000268070, 0xc00087af00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1(0x1f95050, 0xc000268070, 0xc00087ae00)
/home/circleci/project/pkg/server/http/middleware/request_id.go:40 +0x20c
net/http.HandlerFunc.ServeHTTP(0xc000383fc8, 0x1f95050, 0xc000268070, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1f981a0, 0xc0003b0000, 0xc00087ae00)
/home/circleci/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x299
net/http.HandlerFunc.ServeHTTP(0xc0004ff7d0, 0x1f981a0, 0xc0003b0000, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1(0x1f981a0, 0xc0003b0000, 0xc00087ae00)
/home/circleci/project/pkg/logging/http.go:49 +0x2b4
net/http.HandlerFunc.ServeHTTP(0xc0004ff800, 0x1f981a0, 0xc0003b0000, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/extprom/http.(*defaultInstrumentationMiddleware).NewHandler.func1(0x7f4df9545760, 0xc000c740a0, 0xc00087ae00)
/home/circleci/project/pkg/extprom/http/instrument_server.go:108 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc0004ff8c0, 0x7f4df9545760, 0xc000c740a0, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7f4df9545760, 0xc000c74050, 0xc00087ae00)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:198 +0xee
net/http.HandlerFunc.ServeHTTP(0xc0004ffbc0, 0x7f4df9545760, 0xc000c74050, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x7f4df9545760, 0xc000c74000, 0xc00087ae00)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xdf
net/http.HandlerFunc.ServeHTTP(0xc0004ffe30, 0x7f4df9545760, 0xc000c74000, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1(0x1f9a450, 0xc000486000, 0xc00087ae00)
/home/circleci/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:165 +0xee
net/http.HandlerFunc.ServeHTTP(0xc000604150, 0x1f9a450, 0xc000486000, 0xc00087ae00)
/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1(0x1f9a450, 0xc000486000, 0xc00087ad00)
/home/circleci/project/pkg/tracing/http.go:46 +0x54c
github.com/prometheus/common/route.(*Router).handle.func1(0x1f9a450, 0xc000486000, 0xc00087a000, 0x0, 0x0, 0x0)
/home/circleci/go/pkg/mod/github.com/prometheus/common@v0.21.0/route/route.go:83 +0x27f
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000099b60, 0x1f9a450, 0xc000486000, 0xc00087a000)
/home/circleci/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc000537b80, 0x1f9a450, 0xc000486000, 0xc00087a000)
/home/circleci/go/pkg/mod/github.com/prometheus/common@v0.21.0/route/route.go:121 +0x4c
net/http.(*ServeMux).ServeHTTP(0xc0002b1840, 0x1f9a450, 0xc000486000, 0xc00087a000)
/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000486540, 0x1f9a450, 0xc000486000, 0xc00087a000)
/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0008aa000, 0x1fa1310, 0xc000850880)
/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:3013 +0x39b

```

</p>
</details>

**Comment by yeya24** [comment]
Seems this relates to the `stores` API. Need more investigation and help wanted!
