### ISSUE TITLE
Compactor: - out-of-order chunks - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dllegru** [thanos-io/thanos#4807]
"Compactor"

**Thanos, Prometheus and Golang version used**:
thanos Version: 0.23.1

**Object Storage Provider**:
GCS

**What happened**:
Thanos Compactor pod halts with `panic: runtime error: invalid memory address or nil pointer dereference` on `err="error executing compaction: compaction: group 0@13241799951977185062: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compact/compact/0@13241799951977185062/01F05QRPYDNVRCV9AE74EMXCTE: 1/3320 series have an average of 1.000 out-of-order chunks: 0.000 of these are exact duplicates (in terms of data and time range)"`

**What you expected to happen**:
continue working/compacting

**How to reproduce it (as minimally and precisely as possible)**:
Happened just after upgrading from `v0.21.1` to `v0.23.1.`  

**Full logs to relevant components**:

<details>Logs
<p>

```
level=info ts=2021-10-28T14:16:08.672429188Z caller=factory.go:49 msg="loading bucket configuration"
level=info ts=2021-10-28T14:16:08.673861589Z caller=compact.go:385 msg="retention policy of raw samples is enabled" duration=168h0m0s
level=info ts=2021-10-28T14:16:08.673922545Z caller=compact.go:388 msg="retention policy of 5 min aggregated samples is enabled" duration=168h0m0s
level=info ts=2021-10-28T14:16:08.674083904Z caller=compact.go:391 msg="retention policy of 1 hour aggregated samples is enabled" duration=168h0m0s
level=info ts=2021-10-28T14:16:08.676411529Z caller=compact.go:559 msg="starting compact node"
level=info ts=2021-10-28T14:16:08.676449582Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2021-10-28T14:16:08.676758073Z caller=compact.go:999 msg="start sync of metas"
level=info ts=2021-10-28T14:16:08.683558916Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2021-10-28T14:16:08.683718795Z caller=http.go:63 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:10902
ts=2021-10-28T14:16:08.684266798Z caller=log.go:168 service=http/server component=compact level=info msg="TLS is disabled." http2=false
level=info ts=2021-10-28T14:16:19.003274615Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=10.325588333s duration_ms=10325 cached=6910 returned=6910 partial=0
level=info ts=2021-10-28T14:16:27.798277971Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=8.700712423s duration_ms=8700 cached=6910 returned=6910 partial=0
level=info ts=2021-10-28T14:16:35.048235587Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=26.371390307s duration_ms=26371 cached=6910 returned=6835 partial=013241799951977185062
level=info ts=2021-10-28T14:16:35.128859313Z caller=compact.go:1004 msg="start of GC"
level=info ts=2021-10-28T14:16:35.761139327Z caller=compact.go:1027 msg="start of compactions"
level=info ts=2021-10-28T14:16:35.763931163Z caller=compact.go:746 group="0@{domain=\"infrastructure\", environment=\"testing\", prometheus=\"monitoring/thanos\", prometheus_replica=\"prometheus-thanos-0\"}" groupKey=0@13241799951977185062 msg="compaction available and planned; downloading blocks" plan="[01F05A18EDPMTDQXQ0XX7FT9VY (min time: 1615075200000, max time: 1615082400000) 01F05GWY6KZAEC2PDAZKZJRK03 (min time: 1615082400000, max time: 1615089600000) 01F05QRPYDNVRCV9AE74EMXCTE (min time: 1615089600000, max time: 1615096800000) 01F05YME6DY92SJ5AQANGHN63X (min time: 1615096800000, max time: 1615104000000)]"
level=warn ts=2021-10-28T14:16:36.568374674Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="error executing compaction: compaction: group 0@13241799951977185062: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compact/compact/0@13241799951977185062/01F05QRPYDNVRCV9AE74EMXCTE: 1/3320 series have an average of 1.000 out-of-order chunks: 0.000 of these are exact duplicates (in terms of data and time range)"
level=info ts=2021-10-28T14:16:36.568466231Z caller=http.go:74 service=http/server component=compact msg="internal server is shutting down" err="error executing compaction: compaction: group 0@13241799951977185062: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compact/compact/0@13241799951977185062/01F05QRPYDNVRCV9AE74EMXCTE: 1/3320 series have an average of 1.000 out-of-order chunks: 0.000 of these are exact duplicates (in terms of data and time range)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x10e0198]

goroutine 34957 [running]:
cloud.google.com/go/storage.(*ObjectHandle).Attrs(0xc000ab7700, 0x2155bc8, 0xc0005ee9c0, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/cloud.google.com/go/storage@v1.10.0/storage.go:796 +0x118
github.com/thanos-io/thanos/pkg/objstore/gcs.(*Bucket).Exists(0xc0005ee540, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0xc00012bd40, 0xc000ab7828, 0xc000062400)
	/home/circleci/project/pkg/objstore/gcs/gcs.go:161 +0x145
github.com/thanos-io/thanos/pkg/objstore.(*metricBucket).Exists(0xc0005ee580, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0x7ff74f67d401, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/objstore.go:438 +0xf7
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists.func1(0x2155bc8, 0xc0005ee9c0, 0x2177b00, 0x2faad20)
	/home/circleci/project/pkg/objstore/tracing.go:63 +0x13d
github.com/thanos-io/thanos/pkg/tracing.DoWithSpan(0x2155bc8, 0xc0005ee9c0, 0x1e152db, 0xd, 0xc000ab7988, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/tracing/tracing.go:88 +0xde
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists(0x21728a0, 0xc0005ee580, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/tracing.go:61 +0xf1
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).loadMeta(0xc00062e2a0, 0x2155bc8, 0xc0005ee9c0, 0x68d1d1bcfe827901, 0x9ffff8867b75b1d7, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/block/fetcher.go:234 +0x2c2
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata.func1(0xc0006d87c0, 0x9c1d25)
	/home/circleci/project/pkg/block/fetcher.go:325 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000f66b70, 0xc001b2a780)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

```

</p>
</details>

**Anything else we need to know**:
This error just happened when upgrading from `v0.21.1` to `v0.23.1` or `v0.23.0`, when deploying the pod to `v0.22.0` is not happening.

**Comment by yeya24** [comment]
```
goroutine 34957 [running]:
cloud.google.com/go/storage.(*ObjectHandle).Attrs(0xc000ab7700, 0x2155bc8, 0xc0005ee9c0, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/cloud.google.com/go/storage@v1.10.0/storage.go:796 +0x118
github.com/thanos-io/thanos/pkg/objstore/gcs.(*Bucket).Exists(0xc0005ee540, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0xc00012bd40, 0xc000ab7828, 0xc000062400)
	/home/circleci/project/pkg/objstore/gcs/gcs.go:161 +0x145
github.com/thanos-io/thanos/pkg/objstore.(*metricBucket).Exists(0xc0005ee580, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0x7ff74f67d401, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/objstore.go:438 +0xf7
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists.func1(0x2155bc8, 0xc0005ee9c0, 0x2177b00, 0x2faad20)
	/home/circleci/project/pkg/objstore/tracing.go:63 +0x13d
github.com/thanos-io/thanos/pkg/tracing.DoWithSpan(0x2155bc8, 0xc0005ee9c0, 0x1e152db, 0xd, 0xc000ab7988, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/tracing/tracing.go:88 +0xde
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists(0x21728a0, 0xc0005ee580, 0x2155bc8, 0xc0005ee9c0, 0xc002027e90, 0x24, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/tracing.go:61 +0xf1
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).loadMeta(0xc00062e2a0, 0x2155bc8, 0xc0005ee9c0, 0x68d1d1bcfe827901, 0x9ffff8867b75b1d7, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/block/fetcher.go:234 +0x2c2
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata.func1(0xc0006d87c0, 0x9c1d25)
	/home/circleci/project/pkg/block/fetcher.go:325 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000f66b70, 0xc001b2a780)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

This doesn't seem like the panic location. Can you please give the full goroutine dumps in the panic time?

**Comment by dllegru** [comment]
Unfortunately I deleted the compaction blocks that were giving me issues in order to bring the service up, and now I can't reproduce the error. 
If I encounter it again, will get the goroutine dumps at the panic time, thanks fro your help.
