### ISSUE TITLE
compactor 0.24.0 segv

### ISSUE THREAD

**Issue by fbs** [thanos-io/thanos#5095]
**Thanos, Prometheus and Golang version used**:

The 0.24.0 image from quay.io

**Object Storage Provider**:

google

**What happened**:

bucket contains some 'corrupt' old blocks. Compactor complains about the block and then crashes instead of halting. With the 0.20.2 image it just halts

```
level=warn ts=2022-01-23T10:27:49.101381485Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="error executing compaction: compaction: group 0@ID926: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compactor/compact/0@ID926/01F73KNWYQG1EKG8KESQ3S1BK5: 1/746544 series have an average of 1.000 out-of-order chunks: 1.000 of these are exact duplicates (in terms of data and time range)"
```

**What you expected to happen**:

No crash, just halting

**How to reproduce it (as minimally and precisely as possible)**:

No clue, cannot share the data blocks involved config for pod:

```
containers:
- args:
  - compact
  - --log.level=info
  - --data-dir=/var/thanos/compactor
  - |
    --objstore.config=type: GCS
    config:
      bucket: NAME
  - --retention.resolution-raw=0d
  - --retention.resolution-5m=0d
  - --retention.resolution-1h=0d
  - --bucket-web-label=NAME
  - --compact.concurrency=10
  - --delete-delay=48h
  - --wait
  image: quay.io/thanos/thanos:v0.24.0
```

**Full logs to relevant components**:

<details>Logs
<p>

```
level=info ts=2022-01-23T10:17:52.700600023Z caller=compact.go:992 group="0@{private_labels"}" groupKey=0@ID926 msg="compaction available and planned; downloading blocks" plan="[01F73KNWYQG1EKG8KESQ3S1BK5 (min time: 1622534400000, max time: 1622541600000) 01FT33RVDWVDHCADKMEX3WKS0H (min time: 1622541600000, max time: 1622563200000)]"

...
Few other planned compactions get executed, no new plans are created however
...

level=warn ts=2022-01-23T10:27:49.101381485Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="error executing compaction: compaction: group 0@ID926: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compactor/compact/0@ID926/01F73KNWYQG1EKG8KESQ3S1BK5: 1/746544 series have an average of 1.000 out-of-order chunks: 1.000 of these are exact duplicates (in terms of data and time range)"
level=info ts=2022-01-23T10:27:49.101496243Z caller=http.go:74 service=http/server component=compact msg="internal server is shutting down" err="error executing compaction: compaction: group 0@ID926: blocks with out-of-order chunks are dropped from compaction:  /var/thanos/compactor/compact/0@ID926/01F73KNWYQG1EKG8KESQ3S1BK5: 1/746544 series have an average of 1.000 out-of-order chunks: 1.000 of these are exact duplicates (in terms of data and time range)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x11c4118]

goroutine 1455581 [running]:
cloud.google.com/go/storage.(*ObjectHandle).Attrs(0xc000895700, 0x233aef8, 0xc0064c6d20, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/cloud.google.com/go/storage@v1.10.0/storage.go:796 +0x118
github.com/thanos-io/thanos/pkg/objstore/gcs.(*Bucket).Exists(0xc0006205c0, 0x233aef8, 0xc0064c6d20, 0xc004d87ef0, 0x24, 0xc0004317a0, 0xc000895828, 0xc00007c800)
	/home/circleci/project/pkg/objstore/gcs/gcs.go:162 +0x145
github.com/thanos-io/thanos/pkg/objstore.(*metricBucket).Exists(0xc000620600, 0x233aef8, 0xc0064c6d20, 0xc004d87ef0, 0x24, 0x7fb400306801, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/objstore.go:438 +0xf7
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists.func1(0x233aef8, 0xc0064c6d20, 0x235ec40, 0x32650e0)
	/home/circleci/project/pkg/objstore/tracing.go:63 +0x13d
github.com/thanos-io/thanos/pkg/tracing.DoWithSpan(0x233aef8, 0xc0064c6d20, 0x1f7129c, 0xd, 0xc000895988, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/tracing/tracing.go:88 +0xde
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists(0x2359a80, 0xc000620600, 0x233aef8, 0xc0064c6d20, 0xc004d87ef0, 0x24, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/tracing.go:61 +0xf1
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).loadMeta(0xc000c1e230, 0x233aef8, 0xc0064c6d20, 0x5ff96f2055b77b01, 0x18082b4a17e102a2, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/block/fetcher.go:236 +0x2c2
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata.func1(0x0, 0x0)
	/home/circleci/project/pkg/block/fetcher.go:327 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00a2bb2c0, 0xc0035ed640)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

</p>
</details>

**Comment by fbs** [comment]
Just saw another crash without any indication of a bad block. It finished uploading a compacted block and marking the old ones for deletion:


```
level=info ts=2022-01-23T22:04:23.160154252Z caller=fetcher.go:481 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2m24.108220257s duration_ms=144108 cached=33780 returned=28767 partial=1
level=info ts=2022-01-23T22:04:43.705492394Z caller=compact.go:1101 ... 2 msg="uploaded block" result_block=01FT4F76Z4EX1NK720C7VS0YMB duration=1m18.534998174s duration_ms=78534
level=info ts=2022-01-23T22:04:44.604720675Z caller=block.go:209 group=... msg="block has been marked for deletion" block=01FN49E4PGBZ7MX8CG71ZR8BMK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x11c4118]

goroutine 1572047 [running]:
cloud.google.com/go/storage.(*ObjectHandle).Attrs(0xc003df1700, 0x233ae88, 0xc0002bac00, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/cloud.google.com/go/storage@v1.10.0/storage.go:796 +0x118
github.com/thanos-io/thanos/pkg/objstore/gcs.(*Bucket).Exists(0xc00061c100, 0x233ae88, 0xc0002bac00, 0xc004707aa0, 0x24, 0xc00053e0c0, 0xc003df1828, 0x32371a0)
	/home/circleci/project/pkg/objstore/gcs/gcs.go:162 +0x145
github.com/thanos-io/thanos/pkg/objstore.(*metricBucket).Exists(0xc000b98000, 0x233ae88, 0xc0002bac00, 0xc004707aa0, 0x24, 0x7fd484e26e01, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/objstore.go:438 +0xf7
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists.func1(0x233ae88, 0xc0002bac00, 0x235ec40, 0x32650e0)
	/home/circleci/project/pkg/objstore/tracing.go:63 +0x13d
github.com/thanos-io/thanos/pkg/tracing.DoWithSpan(0x233ae88, 0xc0002bac00, 0x1f7129c, 0xd, 0xc003df1988, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/tracing/tracing.go:88 +0xde
github.com/thanos-io/thanos/pkg/objstore.TracingBucket.Exists(0x2359a80, 0xc000b98000, 0x233ae88, 0xc0002bac00, 0xc004707aa0, 0x24, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/objstore/tracing.go:61 +0xf1
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).loadMeta(0xc00021e690, 0x233ae88, 0xc0002bac00, 0xae673ac6a0637d01, 0xd3f1cae821b1da53, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/block/fetcher.go:236 +0x2c2
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata.func1(0xc0030b63e0, 0x1f69f50)
	/home/circleci/project/pkg/block/fetcher.go:327 +0xe5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc002a77b00, 0xc001ecd080)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

```

**Comment by GiedriusS** [comment]
It would be interesting to add https://github.com/fsouza/fake-gcs-server to our e2e testing suite and see whether it is reproducible :thinking:
