### ISSUE TITLE
Combine memcached/redis with in-memory cache

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5509]
### Is your proposal related to a problem?

Our current Memcached & Redis implementations are good at reducing cost however they don't improve query durations as much because each time a query comes in, Thanos Store has to retrieve each key from Memcached/Redis. This saturates the network. We could do better by caching some data in memory so that it wouldn't be needed to retrieve data each time.

### Describe the solution you'd like

For Redis we could use [client side caching](https://redis.io/docs/manual/client-side-caching/) - the server tracks requested keys and then sends us a notification if a key expires.

For Memcached, we could save keys in memory during SetAsync(). Only downside - Memcached could expire some keys while we still have them in memory. In our case, since we use `--max-time` and `--min-time`, it means that TTLs don't matter as much because the users only see the data from Thanos Store after a few days had passed.

### Describe alternatives you've considered

Groupcache - however it is very slow due to contention on one `map` ([link](https://dgraph.io/blog/post/introducing-ristretto-high-perf-go-cache/)) and because retrieval happens key-by-key. I have tried implementing multi-key fetch in our thanos-community fork but it is still not finished because of the complexity. As an alternative solution, we could implement this which is somewhere in the middle.

### Additional context

N/A

**Comment by fpetkovski** [comment]
A custom implementation of multi-level caching might be good for this. We could have a new implementation of `cache.Cache` which wraps multiple concrete caches and uses them in the order in which they are specified.

**Comment by GiedriusS** [comment]
@rueian I have tried it out however I get a panic:

```
panic: multi key command with different key slots are not allowed                                                                               
goroutine 33284 [running]:                                                                                                                      
github.com/rueian/rueidis/internal/cmds.check(...)                                                                                              
/home/giedrius/go/pkg/mod/github.com/rueian/rueidis@v0.0.64/internal/cmds/cmds.go:224                                                           
github.com/rueian/rueidis/internal/cmds.Mget.Key({0xc0f8a96498?, 0xc228?, 0xf9d7?}, {0xc0c41b25c0, 0x2, 0x8acdfb?})   
```

Mhm, how could we know what key slots our cache keys have?

**Comment by rueian** [comment]
> @rueian I have tried it out however I get a panic:
> 
> ```
> panic: multi key command with different key slots are not allowed                                                                               
> goroutine 33284 [running]:                                                                                                                      
> github.com/rueian/rueidis/internal/cmds.check(...)                                                                                              
> /home/giedrius/go/pkg/mod/github.com/rueian/rueidis@v0.0.64/internal/cmds/cmds.go:224                                                           
> github.com/rueian/rueidis/internal/cmds.Mget.Key({0xc0f8a96498?, 0xc228?, 0xf9d7?}, {0xc0c41b25c0, 0x2, 0x8acdfb?})   
> ```
> 
> Mhm, how could we know what key slots our cache keys have?

Hi @GiedriusS, I guess you are connecting to a redis cluster and unfortunately redis cluster does not allow MGET command.

I will see what I can do for this use case.

**Comment by GiedriusS** [comment]
Yeah, I had to set up Redis Cluster because it handles distributing load according to hashes for the client if I understood correctly :/ I was under the initial impression that the client itself needs to do it but it seems like in the Redis world, Redis Cluster takes care of that for the client

**Comment by rueian** [comment]
> Yeah, I had to set up Redis Cluster because it handles distributing load according to hashes for the client if I understood correctly :/ I was under the initial impression that the client itself needs to do it but it seems like in the Redis world, Redis Cluster takes care of that for the client

Hi @GiedriusS,

Redis Cluster nodes only check if the incoming key slot belongs to them and redis client is responsible for sending commands to the right node.

---

I have added a new `MGetCache` helper in rueidis v0.0.65 and also have updated the above example. This should work with Reids Cluster now. Could you have a try?

**Comment by GiedriusS** [comment]
Nice, it works fantastic! Thank you so much for your prompt responses and amazing library :beers: Maybe you have a donation link somewhere? (: FYI here's a graph showing network usage on my servers running Thanos: ![Screenshot from 2022-07-25 15-17-29](https://user-images.githubusercontent.com/2377233/180775841-ef01b18a-d130-47c4-9e8c-1b7b75a8117c.png). In my case I have Grafana instances evaluating alerts using historical data in S3. So, now instead of retrieving index cache items over and over again, they are downloaded once to memory and the hot items are kept there. This improves the situation a lot! You can probably guess when Rueidis with client-side caching has been enabled. I will now work on a PR to add this functionality to Thanos.

The only thing that is missing in rueidis IMO is the ability to use something other than the in-memory cache. Perhaps that could be exposed as an interface through client options so that we could try different cache providers such as [Badger](https://github.com/dgraph-io/badger)? If you would be open to such a change then I could try implementing it. But anyway, that's for another time :smile:

**Comment by rueian** [comment]
Happy to see it works! I don't have a donation link but if you can share rueidis with your friends that would be my honor.

> Perhaps that could be exposed as an interface through client options so that we could try different cache providers such as [Badger](https://github.com/dgraph-io/badger)?

Good idea!  Currently, there is only an internal interface:
https://github.com/rueian/rueidis/blob/6517919074ccc7663f8354fbe7367c153f729129/lru.go#L21-L28

But I think it won't have many differences if I made it exposed publicly.

**Comment by GiedriusS** [comment]
I have noticed a small dead-lock in rueidis from the new MGet helper. Uploading a goroutine dump from my Thanos Store. I'll try looking into it but uploading this in advance :pray: I hope that you'll have some time to take a loo
[goroutine.txt](https://github.com/thanos-io/thanos/files/9206279/goroutine.txt)
k

**Comment by rueian** [comment]
Hi @GiedriusS,

I am looking into that, but currently, I haven't found the cause. Could you also try to remove the ReadTimeout and see if it happens again?

**Comment by rueian** [comment]
Hi @GiedriusS,

Bugs related to the ReadTimeout has been fixed in v0.0.68. Could you take a try?

**Comment by GiedriusS** [comment]
Thank you so much! Will take a look. I only got bit by that problem twice, I think. A bit busy but I'm also about to submit a proposal to Thanos for supporting multiple clients for the same caching systems so that we could finally get rueidis into Thanos.

**Comment by yeya24** [comment]
I think we still want to implement a two layer cache when using memcached?

**Comment by yeya24** [comment]
We added multi level cache implementation in Cortex, like @fpetkovski it is just a wrapper. https://github.com/cortexproject/cortex/pull/5451

We need this as we are using memcached as caches so lacking of client side cache support like Redis does.
