### ISSUE TITLE
Compact: crash when running at high concurrency

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [thanos-io/thanos#5735]
**Thanos, Prometheus and Golang version used**:

```
/opt/prometheus/thanos/thanos --version
thanos, version 0.28.0 (branch: HEAD, revision: 7f58065e691ab68c15ed01c4a27c236add810137)
  build user:       root@38565b300166
  build date:       20220826-17:54:10
  go version:       go1.18.5
  platform:         linux/amd64
```

**Object Storage Provider**:

GCS

**What happened**:

We run thanos-compact at high concurrency to process a backlog. Settings: `--compact.concurrency=16 --compact.blocks-fetch-concurrency=12 --downsample.concurrency=6 --block-files-concurrency=12 --block-meta-fetch-concurrency=128`.

We get a crash with:

```
fatal error: concurrent map read and map write
```

**What you expected to happen**:

Thanos compact does not crash.

**How to reproduce it (as minimally and precisely as possible)**:

No easy reproducer.

**Full logs to relevant components**:

<details>Logs
<p>

```
fatal error: concurrent map read and map write

goroutine 273 [running]:
runtime.throw({0x2100889?, 0xc00ef337b8?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00ef33788 sp=0xc00ef33758 pc=0x4386b1
runtime.mapaccess2(0x1d6a580?, 0xc00ad67dd0?, 0x0?)
        /usr/local/go/src/runtime/map.go:476 +0x205 fp=0xc00ef337c8 sp=0xc00ef33788 pc=0x40ed25
github.com/thanos-io/thanos/pkg/compact.(*tsdbBasedPlanner).plan(0xc000db4690, 0xc02e21e000?, {0xc02be8a000, 0x965, 0xa00})
        /app/pkg/compact/planner.go:59 +0xde fp=0xc00ef338b8 sp=0xc00ef337c8 pc=0x14021be
github.com/thanos-io/thanos/pkg/compact.(*tsdbBasedPlanner).Plan(0xc000db4690, {0xc00de1b400?, 0xc00b903728?}, {0xc02be8a000, 0x965, 0xa00})
        /app/pkg/compact/planner.go:53 +0x4d fp=0xc00ef338f0 sp=0xc00ef338b8 pc=0x140208d
github.com/thanos-io/thanos/pkg/compact.(*CompactionProgressCalculator).ProgressCalculate(0xc000e820f0, {0x2586230, 0xc000db41e0}, {0xc0083ef800, 0x49, 0xc000e8a180?})
        /app/pkg/compact/compact.go:539 +0x44b fp=0xc00ef33d98 sp=0xc00ef338f0 pc=0x13f7d4b
main.runCompact.func14.1()
        /app/cmd/thanos/compact.go:567 +0xc6 fp=0xc00ef33e28 sp=0xc00ef33d98 pc=0x1b29066
github.com/thanos-io/thanos/pkg/runutil.Repeat(0x257ea00?, 0xc00065c6c0, 0xc00ef33f30)
        /app/pkg/runutil/runutil.go:74 +0x90 fp=0xc00ef33ec8 sp=0xc00ef33e28 pc=0x13d0730
main.runCompact.func14()
        /app/cmd/thanos/compact.go:555 +0x17c fp=0xc00ef33f88 sp=0xc00ef33ec8 pc=0x1b28f7c
github.com/oklog/run.(*Group).Run.func1({0xc000dea820?, 0xc000de8be0?})
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x2f fp=0xc00ef33fc0 sp=0xc00ef33f88 pc=0x60b32f
github.com/oklog/run.(*Group).Run.func2()
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:39 +0x2e fp=0xc00ef33fe0 sp=0xc00ef33fc0 pc=0x60b2ce
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00ef33fe8 sp=0xc00ef33fe0 pc=0x46b681
created by github.com/oklog/run.(*Group).Run
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x22a
```

</p>
</details>

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
I'm pretty sure it's `GatherNoCompactionMarkFilter`:

- https://github.com/thanos-io/thanos/blob/dfb7e9d26a7400d8bb78f3a43241481511eea628/pkg/compact/planner.go#L48
- https://github.com/thanos-io/thanos/blob/d848518efb21efd29f68487dc80f1f85a8106424/pkg/compact/compact.go#L1377
- https://github.com/thanos-io/thanos/blob/d848518efb21efd29f68487dc80f1f85a8106424/pkg/compact/compact.go#L1417

While we lock the writes within `Filter()`, we return `noCompactMarkedMap` directly to the consumer from `NoCompactMarkedBlocks`.

We can probably fix this by copying `noCompactMarkedMap` before returning it.
