### ISSUE TITLE
Getting  panic: send on closed channel in Thanos Store  & memory issue

### ISSUE THREAD

**Issue by Nikhils09** [thanos-io/thanos#5810]
**Thanos and Prometheus version used**:
- Prometheus: 2.38.0
- Thanos: 0.28.0

**Object Storage Provider**: S3

**What happened**: I'm running Pometheus and Thanos on AWS EC2, I'm facing some issues with Thanos Store, It's consuming very high memory, I have provided it 16 GB of memory but it's failing with  **panic: send on closed channel** error whenever I try to access historical data in Grafana Dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
I'm using following command to run Thanos Store:
```
thanos store --data-dir /var/thanos/store  --index-cache-size=4GB  --objstore.config-file /etc/prometheus/bucket.yaml --http-address    0.0.0.0:19191 --grpc-address    0.0.0.0:19090
```
It works fine until you try to access data older than one month (historical data) in Grafana dashboards.

**Full logs to relevant components**:

<details>Logs
<p>

```
thanos[1236]: level=debug ts=2022-10-21T14:07:12.317425646Z caller=bucket.go:1132 msg="stats query processed" request="min_time:1508533200000 max_time:1666303200000 matchers:<name:\"__name__\" value:\"jira_dashboard_view_count_total\" > aggregates:COUNTER " stats="&{blocksQueried:12 postingsTouched:12 PostingsTouchedSizeSum:224B postingsToFetch:0 postingsFetched:0 PostingsFetchedSizeSum:0B postingsFetchCount:0 PostingsFetchDurationSum:0s cachedPostingsCompressions:0 cachedPostingsCompressionErrors:0 CachedPostingsOriginalSizeSum:0B CachedPostingsCompressedSizeSum:0B CachedPostingsCompressionTimeSum:0s cachedPostingsDecompressions:12 cachedPostingsDecompressionErrors:0 CachedPostingsDecompressionTimeSum:14.518µs seriesTouched:152 SeriesTouchedSizeSum:27KiB718B seriesFetched:0 SeriesFetchedSizeSum:0B seriesFetchCount:0 SeriesFetchDurationSum:0s chunksTouched:2757 ChunksTouchedSizeSum:1MiB196KiB616B chunksFetched:2757 ChunksFetchedSizeSum:1MiB406KiB545B chunksFetchCount:12 ChunksFetchDurationSum:442.22559ms GetAllDuration:61.802978ms mergedSeriesCount:64 mergedChunksCount:2757 MergeDuration:5.5594ms}" err=null
thanos[1236]: panic: send on closed channel
thanos[1236]: goroutine 5450 [running]:
thanos[1236]: github.com/minio/minio-go/v7.(*Object).doGetRequest(_, {{0xc0cfd10000, 0x3e80, 0x3e80}, 0x330680, 0x0, 0x1, 0x0, 0x1,0x0, ...})
thanos[1236]:         /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.32-0.20220706200439-ef3e45ed9cdb/api-get-object.go:319 +0xdc
thanos[1236]: github.com/minio/minio-go/v7.(*Object).Read(0xc0c9f8b340, {0xc0cfd10000?, 0x16b6d95?, 0xc0cfd14003?})
thanos[1236]:         /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.32-0.20220706200439-ef3e45ed9cdb/api-get-object.go:399 +0x248
thanos[1236]: github.com/thanos-io/objstore.(*timingReadCloser).Read(0xc000687180, {0xc0cfd10000?, 0x6?, 0xc0ad18fb78?})
thanos[1236]:         /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/objstore.go:650 +0x32
thanos[1236]: github.com/thanos-io/objstore.(*tracingReadCloser).Read(0xc0c51c3700, {0xc0cfd10000?, 0x8?, 0x7f59df3d2f18?})
thanos[1236]:         /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/tracing.go:138 +0x32
thanos[1236]: bufio.(*Reader).Read(0xc0009c3b00, {0xc0cfd14094, 0x3d6, 0xc06489c12f?})
thanos[1236]:         /usr/local/go/src/bufio/bufio.go:236 +0x1b4
thanos[1236]: io.ReadAtLeast({0x256b6c0, 0xc0009c3b00}, {0xc0cfd14000, 0x46a, 0x10000}, 0x46a)
thanos[1236]:         /usr/local/go/src/io/io.go:331 +0x9a
thanos[1236]: io.ReadFull(...)
thanos[1236]:         /usr/local/go/src/io/io.go:350
thanos[1236]: github.com/thanos-io/thanos/pkg/store.(*bucketChunkReader).loadChunks(0xc0015b32c0, {0x2586188, 0xc0c51c2fc0}, {0xc0c8a80000, 0x390d, 0x53a?}, {0xc0882844a0, 0x1, 0x2}, 0x2, ...)
thanos[1236]:         /app/pkg/store/bucket.go:2610 +0x747
thanos[1236]: github.com/thanos-io/thanos/pkg/store.(*bucketChunkReader).load.func3()
thanos[1236]:         /app/pkg/store/bucket.go:2538 +0xab
thanos[1236]: golang.org/x/sync/errgroup.(*Group).Go.func1()
thanos[1236]:         /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64
thanos[1236]: created by golang.org/x/sync/errgroup.(*Group).Go
thanos[1236]:         /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5
systemd[1]: store.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: store.service: Failed with result 'exit-code'.
```

</p>
</details>

**Environment**:
- OS : Ubuntu 20.04.5

**Comment by matej-g** [comment]
Hi, this is fixed in `0.28.1` - https://github.com/thanos-io/thanos/releases/tag/v0.28.1 - please update your version. Duplicates https://github.com/thanos-io/thanos/issues/5701.
