### ISSUE TITLE
thanos query engine issue "runtime panic in engine"

### ISSUE THREAD

**Issue by Kot-o-pes** [thanos-io/thanos#6073]
**Thanos, Prometheus and Golang version used**:
v0.30

**Object Storage Provider**:
ceph
**What happened**:
after switching from query.engine prometheus to thanos requests are failing with index out of range error and query consumes lots of memory 
**What you expected to happen**:
query not failing requests
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

Uncomment if you would like to post collapsible logs:

<details>Logs
<p>

```
an 25 19:54:07  thanos-query[50014]: {"caller":"engine.go:361","err":"runtime error: index out of range [30885] with length 30704","expr":"container_memory_swap{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"} * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, node, pod) (kube_pod_info{node!=\"\"}))","level":"error","msg":"runtime panic in engine","stacktrace":"goroutine 18424784 [running]:\ngithub.com/thanos-community/promql-engine/engine.recoverEngine({0x2bd9640, 0xc000823270}, {0x2bf78e0, 0xc4f436a940}, 0xc4f436ad80)\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:359 +0xc6\npanic({0x2507ae0, 0xc61cbcc918})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).join(0xc4f4f4bf40?, 0xc628400000?, 0x79ae?, 0x18c6318c6318c?, 0xc63a6c2030, {0xc4f4313a50, 0x1, 0x1})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:242 +0x71a\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).initOutputs(0xc4f4f4bf40, {0x2bf41c0, 0xc4f436adc0})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:109 +0x2a5\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series.func1()\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x2e\nsync.(*Once).doSlow(0x23352a0?, 0xc4f436ad01?)\n\t/usr/local/go/src/sync/once.go:74 +0xc2\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series(0xc4f4f4bf40?, {0x2bf41c0?, 0xc4f436adc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x7e\ngithub.com/thanos-community/promql-engine/engine.(*compatibilityQuery).Exec(0xc4f4f7aaf0, {0x2bf4268, 0xc4f435de30})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:204 +0x1c2\ngithub.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).query(0xc0008a7a40, 0xc4f436ee00)\n\t/app/pkg/api/query/v1.go:441 +0x92b\ngithub.com/thanos-io/thanos/pkg/api.GetInstr.func1.1({0x2bee450, 0xc4f436c1a0}, 0xc4ea0627e0?)\n\t/app/pkg/api/api.go:211 +0x50\nnet/http.HandlerFunc.ServeHTTP(0xc1aa8cdfd0?, {0x2bee450?, 0xc4f436c1a0?}, 0x2bce434?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1({0x2be99e0?, 0xc4f4374000}, 0xc4f436ee00)\n\t/app/pkg/logging/http.go:73 +0x2d8\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2be99e0?, 0xc4f4374000?}, 0x2bcecb0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1({0x2be99e0, 0xc4f4374000}, 0xc4f436ed00)\n\t/app/pkg/server/http/middleware/request_id.go:40 +0x542\nnet/http.HandlerFunc.ServeHTTP(0x2184f60?, {0x2be99e0?, 0xc4f4374000?}, 0x4?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x2beddc0, 0xc4f436c180}, 0x490001?)\n\t/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x26f\nnet/http.HandlerFunc.ServeHTTP(0xc00c515520?, {0x2beddc0?, 0xc4f436c180?}, 0xc4f3b867e0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.httpInstrumentationHandler.func1({0x7f86ffc36920?, 0xc4ea064b40}, 0xc4f436ed00)\n\t/app/pkg/extprom/http/instrument_server.go:75 +0x10b\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc4ea064b40?}, 0xc4f435dbf0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7f86ffc36920?, 0xc4ea064af0?}, 0xc4f436ed00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:288 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc4ea064af0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x7f86ffc36920?, 0xc4ea064aa0?}, 0xc4f436ed00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146 +0xb8\nnet/http.HandlerFunc.ServeHTTP(0x22c9b80?, {0x7f86ffc36920?, 0xc4ea064aa0?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.instrumentHandlerInFlight.func1({0x7f86ffc36920, 0xc4ea064aa0}, 0xc4f436ed00)\n\t/app/pkg/extprom/http/instrument_server.go:162 +0x169\nnet/http.HandlerFunc.ServeHTTP(0x2bf1390?, {0x7f86ffc36920?, 0xc4ea064aa0?}, 0xc015c47698?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1({0x2bf1390?, 0xc01ac207e0?}, 0xc4f436ed00)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:238 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2bf1390?, 0xc01ac207e0?}, 0x417d220?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1({0x2bf1390, 0xc01ac207e0}, 0xc4f436ec00)\n\t/app/pkg/tracing/http.go:62 +0x9a2\ngithub.com/prometheus/common/route.(*Router).handle.func1({0x2bf1390, 0xc01ac207e0}, 0xc4f436eb00, {0x0, 0x0, 0x478d4e?})\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:83 +0x18d\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0009b80c0, {0x2bf1390, 0xc01ac207e0}, 0xc4f436eb00)\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc01ac207e0?, {0x2bf1390?, 0xc01ac207e0?}, 0x26a27bf?)\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:126 +0x26\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x2bf1390, 0xc01ac207e0}, 0xc4f436eb00)\n\t/usr/local/go/src/net/http/server.go:2487 +0x149\nnet/http.serverHandler.ServeHTTP({0x2be7c00?}, {0x2bf1390, 0xc01ac207e0}, 0xc4f436eb00)\n\t/usr/local/go/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xcb997fee60, {0x2bf4268, 0xc00110d0e0})\n\t/usr/local/go/src/net/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3102 +0x4db\n","ts":"2023-01-25T16:54:07.113556036Z"}
Jan 25 19:54:07 thanos-query[50014]: {"caller":"engine.go:361","err":"runtime error: index out of range [30213] with length 29988","expr":"count by (cluster, node) (sum by (cpu, node) (node_cpu_seconds_total{job=\"node-exporter\"} * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, node_namespace_pod:kube_pod_info:)))","level":"error","msg":"runtime panic in engine","stacktrace":"goroutine 18661058 [running]:\ngithub.com/thanos-community/promql-engine/engine.recoverEngine({0x2bd9640, 0xc000823270}, {0x2bf78a0, 0xc572734a20}, 0xc5b41a2b80)\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:359 +0xc6\npanic({0x2507ae0, 0xc6223e3fe0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).join(0xc5b41b9c20?, 0xc5ace34000?, 0xebde?, 0x40d95f?, 0xc608f95470, {0xc572732ab0, 0x1, 0x1})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:242 +0x71a\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).initOutputs(0xc5b41b9c20, {0x2bf41c0, 0xc5b41a2bc0})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:109 +0x2a5\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series.func1()\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x2e\nsync.(*Once).doSlow(0x0?, 0x0?)\n\t/usr/local/go/src/sync/once.go:74 +0xc2\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series(0xc5b41b9c20?, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x7e\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).initializeScalarTables(0xc547ed7930, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:200 +0x51\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).initializeTables(0xc547ed7930, {0x2bf41c0, 0xc5b41a2bc0})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:168 +0x45\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Series.func1()\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:91 +0x2e\nsync.(*Once).doSlow(0x2bf4d58?, 0x2bf4d90?)\n\t/usr/local/go/src/sync/once.go:74 +0xc2\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Series(0xc547ed7930?, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:91 +0x7e\ngithub.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).Series(0xc572734ae0?, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/exchange/concurrent.go:41 +0x2c\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).initializeScalarTables(0xc547ed7a00, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:200 +0x51\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).initializeTables(0xc547ed7a00, {0x2bf41c0, 0xc5b41a2bc0})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:168 +0x45\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Series.func1()\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:91 +0x2e\nsync.(*Once).doSlow(0x0?, 0x7f8636d780a8?)\n\t/usr/local/go/src/sync/once.go:74 +0xc2\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Series(0xc547ed7a00?, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/aggregate/hashaggregate.go:91 +0x7e\ngithub.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).Series(0x2bf4268?, {0x2bf41c0?, 0xc5b41a2bc0?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/exchange/concurrent.go:41 +0x2c\ngithub.com/thanos-community/promql-engine/engine.(*compatibilityQuery).Exec(0xc5b41b3680, {0x2bf4268, 0xc5b40a5860})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:204 +0x1c2\ngithub.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).query(0xc0008a7a40, 0xc57274e500)\n\t/app/pkg/api/query/v1.go:441 +0x92b\ngithub.com/thanos-io/thanos/pkg/api.GetInstr.func1.1({0x2bee450, 0xc572703360}, 0xc547855e60?)\n\t/app/pkg/api/api.go:211 +0x50\nnet/http.HandlerFunc.ServeHTTP(0xc57277c9a0?, {0x2bee450?, 0xc572703360?}, 0x2bce434?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1({0x2be99e0?, 0xc55df98a10}, 0xc57274e500)\n\t/app/pkg/logging/http.go:73 +0x2d8\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2be99e0?, 0xc55df98a10?}, 0x2bcecb0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1({0x2be99e0, 0xc55df98a10}, 0xc57274e400)\n\t/app/pkg/server/http/middleware/request_id.go:40 +0x542\nnet/http.HandlerFunc.ServeHTTP(0x2184f60?, {0x2be99e0?, 0xc55df98a10?}, 0x4?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x2beddc0, 0xc572703340}, 0x490001?)\n\t/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x26f\nnet/http.HandlerFunc.ServeHTTP(0xc0011a1040?, {0x2beddc0?, 0xc572703340?}, 0xc5971a0900?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.httpInstrumentationHandler.func1({0x7f86ffc36920?, 0xc5610ef630}, 0xc57274e400)\n\t/app/pkg/extprom/http/instrument_server.go:75 +0x10b\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc5610ef630?}, 0xc5b40a5620?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7f86ffc36920?, 0xc5610ef5e0?}, 0xc57274e400)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:288 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc5610ef5e0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x7f86ffc36920?, 0xc5610ef590?}, 0xc57274e400)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146 +0xb8\nnet/http.HandlerFunc.ServeHTTP(0x22c9b80?, {0x7f86ffc36920?, 0xc5610ef590?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.instrumentHandlerInFlight.func1({0x7f86ffc36920, 0xc5610ef590}, 0xc57274e400)\n\t/app/pkg/extprom/http/instrument_server.go:162 +0x169\nnet/http.HandlerFunc.ServeHTTP(0x2bf1390?, {0x7f86ffc36920?, 0xc5610ef590?}, 0xc53bc29698?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1({0x2bf1390?, 0xc0e1dde8c0?}, 0xc57274e400)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:238 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2bf1390?, 0xc0e1dde8c0?}, 0x417d220?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1({0x2bf1390, 0xc0e1dde8c0}, 0xc57274e300)\n\t/app/pkg/tracing/http.go:62 +0x9a2\ngithub.com/prometheus/common/route.(*Router).handle.func1({0x2bf1390, 0xc0e1dde8c0}, 0xc57274e200, {0x0, 0x0, 0x478d4e?})\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:83 +0x18d\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0009b80c0, {0x2bf1390, 0xc0e1dde8c0}, 0xc57274e200)\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc0e1dde8c0?, {0x2bf1390?, 0xc0e1dde8c0?}, 0x268c113?)\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:126 +0x26\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x2bf1390, 0xc0e1dde8c0}, 0xc57274e200)\n\t/usr/local/go/src/net/http/server.go:2487 +0x149\nnet/http.serverHandler.ServeHTTP({0x2be7c00?}, {0x2bf1390, 0xc0e1dde8c0}, 0xc57274e200)\n\t/usr/local/go/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc155889900, {0x2bf4268, 0xc00110d0e0})\n\t/usr/local/go/src/net/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3102 +0x4db\n","ts":"2023-01-25T16:54:07.055055181Z"}
Jan 25 19:54:06  thanos-query[50014]: {"caller":"engine.go:361","err":"runtime error: index out of range [31133] with length 30704","expr":"container_memory_swap{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"} * on (namespace, pod) group_left (node) topk by (namespace, pod) (1, max by (namespace, node, pod) (kube_pod_info{node!=\"\"}))","level":"error","msg":"runtime panic in engine","stacktrace":"goroutine 18782937 [running]:\ngithub.com/thanos-community/promql-engine/engine.recoverEngine({0x2bd9640, 0xc000823270}, {0x2bf78e0, 0xc5bc707300}, 0xc5c1771bc0)\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:359 +0xc6\npanic({0x2507ae0, 0xc59c5d77e8})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).join(0xc03cea3cc0?, 0xc56a9d2000?, 0x79ae?, 0x6318c6318c63?, 0xc5a95482d0, {0xc0390ca250, 0x1, 0x1})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:242 +0x71a\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).initOutputs(0xc03cea3cc0, {0x2bf41c0, 0xc5c1771c40})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:109 +0x2a5\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series.func1()\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x2e\nsync.(*Once).doSlow(0x23352a0?, 0xc5c1771c01?)\n\t/usr/local/go/src/sync/once.go:74 +0xc2\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/thanos-community/promql-engine/execution/binary.(*vectorOperator).Series(0xc03cea3cc0?, {0x2bf41c0?, 0xc5c1771c40?})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/execution/binary/vector.go:78 +0x7e\ngithub.com/thanos-community/promql-engine/engine.(*compatibilityQuery).Exec(0xc03ce89e00, {0x2bf4268, 0xc03908ecc0})\n\t/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/engine/engine.go:204 +0x1c2\ngithub.com/thanos-io/thanos/pkg/api/query.(*QueryAPI).query(0xc0008a7a40, 0xc511c80400)\n\t/app/pkg/api/query/v1.go:441 +0x92b\ngithub.com/thanos-io/thanos/pkg/api.GetInstr.func1.1({0x2bee450, 0xc0b484ca00}, 0xc05e2d6870?)\n\t/app/pkg/api/api.go:211 +0x50\nnet/http.HandlerFunc.ServeHTTP(0xc0b4818cd0?, {0x2bee450?, 0xc0b484ca00?}, 0x2bce434?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/logging.(*HTTPServerMiddleware).HTTPMiddleware.func1({0x2be99e0?, 0xc09e353960}, 0xc511c80400)\n\t/app/pkg/logging/http.go:73 +0x2d8\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2be99e0?, 0xc09e353960?}, 0x2bcecb0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/server/http/middleware.RequestID.func1({0x2be99e0, 0xc09e353960}, 0xc511c80300)\n\t/app/pkg/server/http/middleware/request_id.go:40 +0x542\nnet/http.HandlerFunc.ServeHTTP(0x2184f60?, {0x2be99e0?, 0xc09e353960?}, 0x4?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x2beddc0, 0xc0b484c9e0}, 0x490001?)\n\t/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:338 +0x26f\nnet/http.HandlerFunc.ServeHTTP(0xc00c515520?, {0x2beddc0?, 0xc0b484c9e0?}, 0xc03c224240?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.httpInstrumentationHandler.func1({0x7f86ffc36920?, 0xc0b4829e50}, 0xc511c80300)\n\t/app/pkg/extprom/http/instrument_server.go:75 +0x10b\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc0b4829e50?}, 0xc03908ea80?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x7f86ffc36920?, 0xc0b4829e00?}, 0xc511c80300)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:288 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x7f86ffc36920?, {0x7f86ffc36920?, 0xc0b4829e00?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x7f86ffc36920?, 0xc0b4829db0?}, 0xc511c80300)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146 +0xb8\nnet/http.HandlerFunc.ServeHTTP(0x22c9b80?, {0x7f86ffc36920?, 0xc0b4829db0?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/extprom/http.instrumentHandlerInFlight.func1({0x7f86ffc36920, 0xc0b4829db0}, 0xc511c80300)\n\t/app/pkg/extprom/http/instrument_server.go:162 +0x169\nnet/http.HandlerFunc.ServeHTTP(0x2bf1390?, {0x7f86ffc36920?, 0xc0b4829db0?}, 0xc12495b698?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1({0x2bf1390?, 0xc0b507e620?}, 0xc511c80300)\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:238 +0xc5\nnet/http.HandlerFunc.ServeHTTP(0x2bf4268?, {0x2bf1390?, 0xc0b507e620?}, 0x417d220?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/thanos-io/thanos/pkg/tracing.HTTPMiddleware.func1({0x2bf1390, 0xc0b507e620}, 0xc511c80200)\n\t/app/pkg/tracing/http.go:62 +0x9a2\ngithub.com/prometheus/common/route.(*Router).handle.func1({0x2bf1390, 0xc0b507e620}, 0xc511c80100, {0x0, 0x0, 0x478d4e?})\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:83 +0x18d\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0009b80c0, {0x2bf1390, 0xc0b507e620}, 0xc511c80100)\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc0b507e620?, {0x2bf1390?, 0xc0b507e620?}, 0x269b92c?)\n\t/go/pkg/mod/github.com/prometheus/common@v0.37.1/route/route.go:126 +0x26\nnet/http.(*ServeMux).ServeHTTP(0x0?, {0x2bf1390, 0xc0b507e620}, 0xc511c80100)\n\t/usr/local/go/src/net/http/server.go:2487 +0x149\nnet/http.serverHandler.ServeHTTP({0x2be7c00?}, {0x2bf1390, 0xc0b507e620}, 0xc511c80100)\n\t/usr/local/go/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc5e0978fa0, {0x2bf4268, 0xc00110d0e0})\n\t/usr/local/go/src/net/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3102 +0x4db\n","ts":"2023-01-25T16:54:06.555741374Z"}
```

</p>
</details>

**Anything else we need to know**:

**Comment by Kot-o-pes** [comment]
memory usage
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/33171510/214645226-06d6fca9-98e6-494f-99bf-b4ec63f4ea97.png">

**Comment by fpetkovski** [comment]
Hello, thank you reporting this. I believe we could have already fixed the issue [here](https://github.com/thanos-community/promql-engine/pull/128).

Are you able to run a querier from the latest main to verify if you're still seeing the same problem? The docker image is `quay.io/thanos/thanos:main-2023-01-25-3c86904`. If not, we can maybe cut a new release with the latest engine version.

**Comment by fpetkovski** [comment]
The original github issue reports a similar query as the one you're seeing in the error logs: https://github.com/thanos-community/promql-engine/issues/127.

**Comment by Kot-o-pes** [comment]
thank you, im running thanos from systemd on VM, can i build from main branch in order to have this changes?

**Comment by fpetkovski** [comment]
Yes, definitely. this is also a way to try it out.

**Comment by Kot-o-pes** [comment]
ive installed latest version builded form main branch, runtime panic have disappeared from logs but memory consumption for query remains leading to oom issues

**Comment by GiedriusS** [comment]
Closing since there was no response and to keep the issue tracker clean. Please let us know if this issue persists.
