### ISSUE TITLE
LabelValues leads to panic in Receiver during compaction

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#6190]
**Thanos, Prometheus and Golang version used**: 0.30.2

**What happened**: 

We noticed several Receivers panicked and crashed during compaction. Looking at logs, it seems like there was a segmentation fault caused by reading label values while head compaction was taking place.

**What you expected to happen**:

LabelValues can be read safely during compaction, or at least Receivers should not crash.

**How to reproduce it (as minimally and precisely as possible)**:

Probably not easy to reproduce.

**Full logs to relevant components**:

<details>Logs
<p>

```
unexpected fault address 0x7fcd984f4aa2
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fcd984f4aa2 pc=0x402a1b]

goroutine 12720236003 [running]:
runtime.throw({0x25b3c1b?, 0xc2d7bf50f8?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc2d7bf5078 sp=0xc2d7bf5048 pc=0x438431
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x2ec fp=0xc2d7bf50c8 sp=0xc2d7bf5078 pc=0x44e68c
cmpbody()
	/usr/local/go/src/internal/bytealg/compare_amd64.s:53 +0x3b fp=0xc2d7bf50d0 sp=0xc2d7bf50c8 pc=0x402a1b
sort.StringSlice.Less(...)
	/usr/local/go/src/sort/sort.go:319
sort.(*StringSlice).Less(0x40b317?, 0x18?, 0x21198a0?)
	<autogenerated>:1 +0x65 fp=0xc2d7bf5100 sp=0xc2d7bf50d0 pc=0x4d2c45
sort.IsSorted({0x2b1d090, 0xc536877ae8})
	/usr/local/go/src/sort/sort.go:272 +0x56 fp=0xc2d7bf5130 sp=0xc2d7bf5100 pc=0x4d05b6
sort.StringsAreSorted(...)
	/usr/local/go/src/sort/sort.go:345
github.com/thanos-io/thanos/pkg/strutil.MergeUnsortedSlices({0xc516f8f800, 0x12, 0x20})
	/go/src/github.com/thanos-io/thanos/pkg/strutil/merge.go:28 +0x8b fp=0xc2d7bf5180 sp=0xc2d7bf5130 pc=0x18fba8b
github.com/thanos-io/thanos/pkg/store.(*ProxyStore).LabelValues(0xc00061f7a0, {0x2b1dd08, 0xc2f3cfb410}, 0xc3ea1ffa90)
	/go/src/github.com/thanos-io/thanos/pkg/store/proxy.go:541 +0x325 fp=0xc2d7bf5318 sp=0xc2d7bf5180 pc=0x19dc1a5
github.com/thanos-io/thanos/pkg/store.(*instrumentedStoreServer).LabelValues(0x19?, {0x2b1dd08?, 0xc2f3cfb410?}, 0x40a48d?)
	<autogenerated>:1 +0x34 fp=0xc2d7bf5348 sp=0xc2d7bf5318 pc=0x19ea354
github.com/thanos-io/thanos/pkg/store.(*limitedStoreServer).LabelValues(0xc268cf7ba0?, {0x2b1dd08?, 0xc2f3cfb410?}, 0x25b48d6?)
	<autogenerated>:1 +0x34 fp=0xc2d7bf5378 sp=0xc2d7bf5348 pc=0x19e8f94
github.com/thanos-io/thanos/pkg/store.(*ReadWriteTSDBStore).LabelValues(0x40b585?, {0x2b1dd08?, 0xc2f3cfb410?}, 0x8000000000000000?)
	<autogenerated>:1 +0x34 fp=0xc2d7bf53a8 sp=0xc2d7bf5378 pc=0x19eb0b4
github.com/thanos-io/thanos/pkg/store.(*recoverableStoreServer).LabelValues(0x2b18?, {0x2b1dd08?, 0xc2f3cfb410?}, 0xc403f76d30?)
	<autogenerated>:1 +0x35 fp=0xc2d7bf53d8 sp=0xc2d7bf53a8 pc=0x19e9e95
github.com/thanos-io/thanos/pkg/store/storepb._Store_LabelValues_Handler.func1({0x2b1dd08, 0xc2f3cfb410}, {0x24acd20?, 0xc3ea1ffa90})
	/go/src/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go:1147 +0x78 fp=0xc2d7bf5418 sp=0xc2d7bf53d8 pc=0x147fef8
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x2b1dd08, 0xc2f3cfb410}, {0x24acd20, 0xc3ea1ffa90}, 0x24d58b317e859?, 0xc40b1abe30)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x21e fp=0xc2d7bf5558 sp=0xc2d7bf5418 pc=0x139b35e
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1.1.1({0x2b1dd08?, 0xc2f3cfb410?}, {0x24acd20?, 0xc3ea1ffa90?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:27 +0x3a fp=0xc2d7bf5598 sp=0xc2d7bf5558 pc=0x14a759a
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x2b1dd08, 0xc2f3cfb3b0}, {0x24acd20, 0xc3ea1ffa90}, 0x2224760?, 0xc69bffa540)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x21e fp=0xc2d7bf56d8 sp=0xc2d7bf5598 pc=0x139b35e
github.com/thanos-io/thanos/pkg/tracing.UnaryServerInterceptor.func1({0x2b1dd08?, 0xc2f3cfb2f0?}, {0x24acd20, 0xc3ea1ffa90}, 0x0?, 0xffffffffffffffff?)
	/go/src/github.com/thanos-io/thanos/pkg/tracing/grpc.go:30 +0x88 fp=0xc2d7bf5730 sp=0xc2d7bf56d8 pc=0x14e5448
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1.1.1({0x2b1dd08?, 0xc2f3cfb2f0?}, {0x24acd20?, 0xc3ea1ffa90?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:27 +0x3a fp=0xc2d7bf5770 sp=0xc2d7bf5730 pc=0x14a759a
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x2b1dd08, 0xc2f3cfb200}, {0x24acd20, 0xc3ea1ffa90}, 0xc0cb8be230?, 0xc69bffa560)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x21e fp=0xc2d7bf58b0 sp=0xc2d7bf5770 pc=0x139b35e
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1.1.1({0x2b1dd08?, 0xc2f3cfb200?}, {0x24acd20?, 0xc3ea1ffa90?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:27 +0x3a fp=0xc2d7bf58f0 sp=0xc2d7bf58b0 pc=0x14a759a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x2b1dd08, 0xc2f3cfb200}, {0x24acd20, 0xc3ea1ffa90}, 0x7fcd5a20b0b0?, 0xc69bffa580)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87 fp=0xc2d7bf5950 sp=0xc2d7bf58f0 pc=0x1c5bae7
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1.1.1({0x2b1dd08?, 0xc2f3cfb200?}, {0x24acd20?, 0xc3ea1ffa90?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:27 +0x3a fp=0xc2d7bf5990 sp=0xc2d7bf5950 pc=0x14a759a
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.UnaryServerInterceptor.func1({0x2b1dd08?, 0xc2f3cfb200?}, {0x24acd20?, 0xc3ea1ffa90?}, 0x7fcd0596e550?, 0xc69bffa520?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/recovery/interceptors.go:31 +0xa7 fp=0xc2d7bf5a18 sp=0xc2d7bf5990 pc=0x1c60827
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1.1.1({0x2b1dd08?, 0xc2f3cfb200?}, {0x24acd20?, 0xc3ea1ffa90?})
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:27 +0x3a fp=0xc2d7bf5a58 sp=0xc2d7bf5a18 pc=0x14a759a
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainUnaryServer.func1({0x2b1dd08, 0xc2f3cfb200}, {0x24acd20, 0xc3ea1ffa90}, 0xc63e15baf8?, 0x21be1a0?)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:36 +0xbf fp=0xc2d7bf5ab0 sp=0xc2d7bf5a58 pc=0x14a743f
github.com/thanos-io/thanos/pkg/store/storepb._Store_LabelValues_Handler({0x22d4da0?, 0xc0006a1720}, {0x2b1dd08, 0xc2f3cfb200}, 0xc3921919e0, 0xc00082be90)
	/go/src/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go:1149 +0x138 fp=0xc2d7bf5b08 sp=0xc2d7bf5ab0 pc=0x147fdb8
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008e2c40, {0x2b2e7c8, 0xc02bd76820}, 0xc09b4a70e0, 0xc00085c090, 0x3f99170, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf fp=0xc2d7bf5e48 sp=0xc2d7bf5b08 pc=0xf774af
google.golang.org/grpc.(*Server).handleStream(0xc0008e2c40, {0x2b2e7c8, 0xc02bd76820}, 0xc09b4a70e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b fp=0xc2d7bf5f68 sp=0xc2d7bf5e48 pc=0xf7badb
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98 fp=0xc2d7bf5fe0 sp=0xc2d7bf5f68 pc=0xf75018
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc2d7bf5fe8 sp=0xc2d7bf5fe0 pc=0x46b581
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

```

</p>
</details>

**Anything else we need to know**:

This is likely related to using memory that's mmaped and released, either from the head or by applying retention. The root cause is probably somewhere in TSDB, but I wonder if we should reduce reliance on mmaped data and make copies when streaming it out to a client.

**Comment by GiedriusS** [comment]
This is probably one of those grpc-go footguns in play where SendMsg() only actually queues the given message to be sent at some unspecified time in the future effectively taking ownership of a given message instead of returning when the message has been put on the wire 😄

**Comment by yeya24** [comment]
We hit similar issues in Cortex due to TSDB mmap https://github.com/cortexproject/cortex/pull/5119.

**Comment by fpetkovski** [comment]
Yeah seems to be the classic gRPC + mmap combo :(

**Comment by sepich** [comment]
This is easier to reproduce when you have 
```
          - --tsdb.min-block-duration=30m
          - --tsdb.max-block-duration=30m
```
Could happen on 3 of 5 receivers at the same time.

**Comment by mhoffm-aiven** [comment]
We also see this with "TimeRange" and "Info" gRPC calls
