### ISSUE TITLE
Thanos Receive (RouteOnly mode) Panic

### ISSUE THREAD

**Issue by jnyi** [thanos-io/thanos#6942]
**Thanos, Prometheus and Golang version used**:
Thanos Version: 0.32.4/0.32.5
Golang Version: go1.21.3

**Object Storage Provider**: AWS S3

**What happened**: Thanos Receive with route only mode panic frequently, the setup of Receive:

```
      receive
      --debug.name=thanos-writer
      --log.format=logfmt
      --log.level=info
      --http-address=0.0.0.0:10902
      --http-grace-period=5m
      --grpc-address=0.0.0.0:10901
      --grpc-grace-period=5m
      --hash-func=SHA256
      --label
      replica="$(NAME)"
      --receive.default-tenant-id=unknown
      --remote-write.address=0.0.0.0:19291
      --receive-forward-timeout=15s
      --receive.hashrings-algorithm=ketama
      --receive.hashrings-file=/var/lib/tsdb/hashring.json
      --receive.hashrings-file-refresh-interval=3m
      --receive.replication-factor=3
```

**What you expected to happen**: No panic

**How to reproduce it (as minimally and precisely as possible)**: 

**Full logs to relevant components**:
Panic from k8s docker logs

```

```

**Anything else we need to know**:

**Comment by yeya24** [comment]
This seems the line that has caused the panic. https://github.com/klauspost/compress/blob/v1.16.7/s2/writer.go#L505C1-L506C1

But Idk how this could be related.Maybe it is a go runtime bug. I see some issues mentioning it for go 1.21.0 https://github.com/golang/go/issues/62182, but not on amd64 and your version is already go 1.21.3

**Comment by dctrwatson** [comment]
Lots of: `fatal error: traceback did not unwind completely`

But one time did get more:
```
fatal error: slice bounds out of range
fatal error: index out of range
panic during panic
SIGSEGV: segmentation violation
PC=0x472d5c m=9 sigcode=128

goroutine 0 [idle]:
runtime.usleep()
        /usr/local/go/src/runtime/sys_linux_amd64.s:135 +0x3c fp=0xc00118ddb8 sp=0xc00118ddb0 pc=0x472d5c
runtime: g 0: unexpected return pc for runtime.usleep called from 0xc3f06ce4ebcc77b6
stack: frame={sp:0xc00118ddb0, fp:0xc00118ddb8} stack=[0xc00118a000,0xc00118e000)
0x000000c00118dcb0:  0x3c3340f3c227fbf8  0x79bc80d2fdde9458
0x000000c00118dcc0:  0x2dd704326b3009fa  0x17345fc643dff433
0x000000c00118dcd0:  0x3241b266f903f1ae  0x8fc501ce5567bc22
0x000000c00118dce0:  0xa395dd9af6d97aba  0x953d2adbb67eb6c0
0x000000c00118dcf0:  0xc01a1ee400460928  0xcbc78c168ec5bc26
0x000000c00118dd00:  0xf698e3343fa16822  0x426667d3ab61d8bf
0x000000c00118dd10:  0x177a662b55361989  0x47acd314c41d51f7
0x000000c00118dd20:  0xbd52fd18cca6e6a5  0x39f03de62494ad2e
0x000000c00118dd30:  0xc5ea86a4f373a6e4  0x5b1788faeeae30eb
0x000000c00118dd40:  0xe0e5fcf7e312da2b  0xe726c9b9a759e5a5
0x000000c00118dd50:  0x283e9e7ea0398998  0x2694029422d2c0ca
0x000000c00118dd60:  0x80fcd1c94745a41a  0x4c914de599147d77
0x000000c00118dd70:  0xc04b2a9646c165f3  0x66d8d1497674d855
0x000000c00118dd80:  0x00899d5fcbd0b13b  0x1ec6839c21b87faf
0x000000c00118dd90:  0xc188389384810d93  0xdbefaf5fa465a331
0x000000c00118dda0:  0x3599b61340b9afc0  0xcd240136b2b9fd3a
0x000000c00118ddb0: <0xc3f06ce4ebcc77b6 >0x140433104b2f520c
0x000000c00118ddc0:  0xa1606b824380066c  0xc782178cc7735f3b
0x000000c00118ddd0:  0x4f94b88647ff179c  0x36c57536a7b57377
0x000000c00118dde0:  0xed0ccb6daa1e2206  0xb314e84cec4d3134
0x000000c00118ddf0:  0xc5e83fab342ee596  0x5c01897f6b6615cc
0x000000c00118de00:  0x1f5b6e10e1363122  0x4aee5af6695344b2
0x000000c00118de10:  0xcaa70494b921fa78  0xd189d105408cbd11
0x000000c00118de20:  0x181c6f07b4ef7a16  0x1d0d4765832dcd0c
0x000000c00118de30:  0x87060ecd6c84e951  0x274064a173099845
0x000000c00118de40:  0x1e252a1fdca33895  0xd6ccf35a2c68179f
0x000000c00118de50:  0x836e3bab7ed44eb4  0xc056c1a729014758
0x000000c00118de60:  0xc5501cb1b8184f55  0x2919f8a06039fd69
0x000000c00118de70:  0x60660cffa8e2fc2b  0x6dada1c343524be3
0x000000c00118de80:  0xb0d29d92026fd6fd  0xe7524cab3e45f791
0x000000c00118de90:  0xc7dc33955b898e65  0x1aa5aa09fba46f62
0x000000c00118dea0:  0xa2780d11f200ad96  0xf5a944f1d0d62522
0x000000c00118deb0:  0x835d046bf0f64589

goroutine 705932 [running]:
runtime.systemstack_switch
```

**Comment by jnyi** [comment]
ok, looks like this https://github.com/klauspost/compress/pull/867 is the root cause and are fixed in https://github.com/thanos-io/thanos/pull/6950, I saw thanos main picked up the newer go mod but not 0.32.5 or [v0.33.0-rc.0](https://github.com/thanos-io/thanos/releases/tag/v0.33.0-rc.0).

I will cherry pick the updated go mod in order to fix this internally. 

cc @mhoffm-aiven @yeya24 to make sure this gets patched to latest v0.33, thanks

**Comment by fpetkovski** [comment]
Thanks for reporting back the resolution @jnyi

**Comment by jnyi** [comment]
actually it might be a false resolution, the panic seems still happening after i upgraded compress@v1.71.1 but it was very infrequent, I am trying compress@v1.71.4, i will let it run for a bit longer overnight and report.

**Comment by jnyi** [comment]
ok, it panic again with `/go/pkg/mod/github.com/klauspost/compress@v1.17.4/s2/writer.go:505 +0xb5`

stack trace:
```
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x43e1f3]

goroutine 6281927 [running]:
runtime.throw({0x2654fb1?, 0x6d614e6472616873?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc00468de40 sp=0xc00468de10 pc=0x43b39c
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:875 +0x285 fp=0xc00468dea0 sp=0xc00468de40 pc=0x452265
runtime.gopark(0x6e6f636573696c6c?, 0x656b6375625f7364?, 0x74?, 0xa?, 0x61642d676f6c1412?)
	/usr/local/go/src/runtime/proc.go:399 +0xd3 fp=0xc00468dea8 sp=0xc00468dea0 pc=0x43e1f3
runtime: g 6281927: unexpected return pc for runtime.gopark called from 0x696d5f79636e6574
stack: frame={sp:0xc00468dea0, fp:0xc00468dea8} stack=[0xc00460e000,0xc00468e000)
0x000000c00468dda0:  0x0000000000000001  0x0000000000000001
0x000000c00468ddb0:  0x000000c00468de2d  0x000000000046f632 <runtime.systemstack+0x0000000000000032>
0x000000c00468ddc0:  0x000000c00468de00  0x000000000043b6a5 <runtime.fatalthrow+0x0000000000000065>
0x000000c00468ddd0:  0x000000c00468dde0  0x000000c000f7e680
0x000000c00468dde0:  0x000000000043b6e0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c000f7e680
0x000000c00468ddf0:  0x000000000043b39c <runtime.throw+0x000000000000005c>  0x000000c00468de10
0x000000c00468de00:  0x000000c00468de30  0x000000000043b39c <runtime.throw+0x000000000000005c>
0x000000c00468de10:  0x000000c00468de18  0x000000000043b3c0 <runtime.throw.func1+0x0000000000000000>
0x000000c00468de20:  0x0000000002654fb1  0x0000000000000005
0x000000c00468de30:  0x000000c00468de90  0x0000000000452265 <runtime.sigpanic+0x0000000000000285>
0x000000c00468de40:  0x0000000002654fb1  0x6d614e6472616873
0x000000c00468de50:  0x0000000000000000  0x7665642d61696e69
0x000000c00468de60:  0x0000000000091012  0xdc8b969a10401000
0x000000c00468de70:  0x000000c000f7e680  0x5f656d616e5f5f08
0x000000c00468de80:  0x6164676f6c36125f  0x636f645f6e6f6d65
0x000000c00468de90:  0x614c726564616572  0x000000000043e1f3 <runtime.gopark+0x00000000000000d3>
0x000000c00468dea0: <0x696d5f79636e6574 >0x6e6f636573696c6c
0x000000c00468deb0:  0x656b6375625f7364  0x707061030a1b0a74
0x000000c00468dec0:  0x61642d676f6c1412  0x6561642d6e6f6d65
0x000000c00468ded0:  0x0c0a7465736e6f6d  0x1264756f6c63050a
0x000000c00468dee0:  0x0e0a150a73776103  0x72705f64756f6c63
0x000000c00468def0:  0x031272656469766f  0x63150a260a535741
0x000000c00468df00:  0x6f72705f64756f6c  0x65725f7265646976
0x000000c00468df10:  0x57410d126e6f6967  0x5341455f53555f53
0x000000c00468df20:  0x640e0a150a315f54  0x6f7269766e655f62
0x000000c00468df30:  0x440312746e656d6e  0x6264140a1e0a5645
0x000000c00468df40:  0x74616c756765725f  0x616d6f645f79726f
0x000000c00468df50:  0x4c42555006126e69  0x6e65030a0a0a4349
0x000000c00468df60:  0x1d0a766564031276  0x6e6174736e69080a
0x000000c00468df70:  0x322e303111126563  0x3836312e3630312e
0x000000c00468df80:  0x0a160a373737373a  0x756b0f12626f6a03
0x000000c00468df90:  0x736574656e726562  0x0a2a0a73646f702d
0x000000c00468dfa0:  0x656e726562756b17
created by github.com/klauspost/compress/s2.(*Writer).write in goroutine 6281866
	/go/pkg/mod/github.com/klauspost/compress@v1.17.4/s2/writer.go:505 +0xb5

goroutine 1 [chan receive, 45 minutes]:
runtime.gopark(0xc000a3fb68?, 0x4105c5?, 0xc0?, 0x9c?, 0x20?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0012efb00 sp=0xc0012efae0 pc=0x43e1ee
runtime.chanrecv(0xc0007d06c0, 0xc000a3fc00, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc0012efb78 sp=0xc0012efb00 pc=0x4099ad
runtime.chanrecv1(0xc000a3fc10?, 0x9?)
	/usr/local/go/src/runtime/chan.go:442 +0x12 fp=0xc0012efba0 sp=0xc0012efb78 pc=0x4095b2
github.com/oklog/run.(*Group).Run(0xc000011968)
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:43 +0x155 fp=0xc0012efc20 sp=0xc0012efba0 pc=0x622255
main.main()
	/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:159 +0x1878 fp=0xc0012eff40 sp=0xc0012efc20 pc=0x1f0e7b8
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc0012effe0 sp=0xc0012eff40 pc=0x43dd7b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0012effe8 sp=0xc0012effe0 pc=0x471441
```

**Comment by MichaHoffmann** [comment]
I already prepared and built artifacts for 0.33 yesterday; since this is still ongoing ill earmark it for 0.33.1!

**Comment by klauspost** [comment]
Could you try building with `-tags=noasm`?

**Comment by klauspost** [comment]
We have been unable to pinpoint the origin of similar crashes at MinIO. It seems to happen on only select machines and the workaround we've been using is to compile with go 1.19.x which fixes the issue. I've created an issue (link above this post) to see if we can get to the bottom of this!

**Comment by klauspost** [comment]
@dctrwatson - The Go team is asking for Linux kernel versions. I don't know if you have that, but if you do please add it to

https://github.com/golang/go/issues/64781

**Comment by jnyi** [comment]
Confirmed after compile thanos with go 1.19 < 1.20, there is no panic happening ~ 10hrs, previously this would happen more than 20+ in 10 hrs for a deployments with 4 instances.

**Comment by dctrwatson** [comment]
Per the request in https://github.com/golang/go/issues/64781 I added `GODEBUG="gccheckmark=1,gcshrinkstackoff=1,asyncpreemptoff=1"` and we have not had a panic in >24h. We used to see at least a couple per hour.

**Comment by dctrwatson** [comment]
Ran each `GODEBUG` flag separately, seems only `GODEBUG=gcshrinkstackoff=1` is needed to prevent panics for now

**Comment by karsov** [comment]
At my company we were also having a very similar panic for the Thanos Receiver (RouteOnly mode) with version `v0.33.0`.
Interestingly it was happening only in our most active region.
Also, in our case the stack traces were not printed and the last log we had was `fatal: bad g in signal handler` or `fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)`.

Setting the environment variable `GODEBUG=gcshrinkstackoff=1` (as suggested above) seems to have completely resolved the issue. Previously we had a restart every couple of hours, now we have none in 4 days.

**Comment by RodrigoMenezes-Vantage** [comment]
We've been having this happen on `bitnami/thanos:0.35.1-debian-12-r1` as well. It happens consistently across all 3 replicas of thanos-receive-distributor we run.

```
runtime: g42867214: frame.sp=0xc0020c1e50 top=0xc0020c1fe0
	stack=[0xc002042000-0xc0020c2000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0x28d4031?, 0x0?})
	/opt/bitnami/go/src/runtime/panic.go:1077 +0x5c fp=0xc000295d40 sp=0xc000295d10 pc=0x43b7dc
runtime.(*unwinder).finishInternal(0x0?)
	/opt/bitnami/go/src/runtime/traceback.go:568 +0x12a fp=0xc000295d80 sp=0xc000295d40 pc=0x46210a
runtime.(*unwinder).next(0xc000295e28?)
	/opt/bitnami/go/src/runtime/traceback.go:449 +0x235 fp=0xc000295df8 sp=0xc000295d80 pc=0x461f15
runtime.addOneOpenDeferFrame.func1()
	/opt/bitnami/go/src/runtime/panic.go:648 +0x85 fp=0xc000295fc8 sp=0xc000295df8 pc=0x43a985
runtime.systemstack()
	/opt/bitnami/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc000295fd8 sp=0xc000295fc8 pc=0x46fb8a

goroutine 42867214 [running]:
runtime.systemstack_switch()
	/opt/bitnami/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0020c1d60 sp=0xc0020c1d50 pc=0x46fb28
runtime.addOneOpenDeferFrame(0x0?, 0x0?, 0x0?)
	/opt/bitnami/go/src/runtime/panic.go:645 +0x65 fp=0xc0020c1da0 sp=0xc0020c1d60 pc=0x43a8a5
panic({0x23fd040?, 0x4cb1710?})
	/opt/bitnami/go/src/runtime/panic.go:874 +0x14a fp=0xc0020c1e50 sp=0xc0020c1da0 pc=0x43b14a
runtime.panicmem(...)
	/opt/bitnami/go/src/runtime/panic.go:261
runtime.sigpanic()
	/opt/bitnami/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc0020c1eb0 sp=0xc0020c1e50 pc=0x4527f8
created by github.com/klauspost/compress/s2.(*Writer).write in goroutine 11220
	/bitnami/blacksmith-sandox/thanos-0.35.1/pkg/mod/github.com/klauspost/compress@v1.17.7/s2/writer.go:509 +0xb5
```

**Comment by yangtian9999** [comment]
Hi, @RodrigoMenezes-Vantage 
we meet the similar issue.


`stack: frame={sp:0xc0030dfd98, fp:0xc0030dfda8} stack=[0xc003060000,0xc0030e0000)
runtime: g 2704737: unexpected return pc for runtime.systemstack_switch called from 0xc0034965d2
"	/opt/bitnami/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0030dfda8 sp=0xc0030dfd98 pc=0x46fb28"
runtime.systemstack_switch()
goroutine 2704737 [running]:
"	/opt/bitnami/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc000613fd8 sp=0xc000613fc8 pc=0x46fb8a"
runtime.systemstack()
"	/opt/bitnami/go/src/runtime/panic.go:1205 +0x69 fp=0xc000613fc8 sp=0xc000613f78 pc=0x43bd09"
runtime.fatalpanic.func1()
"	/opt/bitnami/go/src/runtime/panic.go:594 +0x2d fp=0xc000613f78 sp=0xc000613f58 pc=0x43a76d"
runtime.printpanics(0xc0030dfe60)
"	/opt/bitnami/go/src/runtime/panic.go:593 +0x17 fp=0xc000613f58 sp=0xc000613f38 pc=0x43a757"
runtime.printpanics(0x3)
goroutine 0 [idle]:
PC=0x43a757 m=7 sigcode=1
SIGSEGV: segmentation violation
panic during panic
"	/opt/bitnami/go/src/runtime/proc.go:398 +0xce fp=0xc0019b7ad8 sp=0xc0019b7ab8 pc=0x43e6ce"
runtime.gopark(0xc?, 0xc002521348?, 0x8?, 0x0?, 0x0?)
goroutine 1 [chan receive, 55 minutes]:
"	/bitnami/blacksmith-sandox/thanos-0.35.0/pkg/mod/github.com/klauspost/compress@v1.17.7/s2/writer.go:509 +0xb5"
created by github.com/klauspost/compress/s2.(*Writer).write in goroutine 232
`

**Comment by yangtian9999** [comment]
Hi guys,
Since env GODEBUG is a workaround setting,
may I know if has any update for this thanos-distributor restart issue?

**Comment by mvv-dvb** [comment]
It looks like this is at least fixed in Go 1.22, which then might indicate the next release of Thanos should be able to run without this ENV set i think.

**Comment by klauspost** [comment]
I have seen strange stuff even on Go 1.22 - so I have (just today) merged a change that ditches the large stack: https://github.com/klauspost/compress/pull/1014

It may not be needed, but I couldn't live with the potential problem going forward even if it was a runtime issue. And since I don't have a clean reproducer I though this might be the best approach.

I will probably make a release before too long, so hopefully we can close this down for good.

**Comment by klauspost** [comment]
For Go 1.22.x I see this bug: https://github.com/golang/go/issues/66383 pop up under prolonged heavy load, FWIW.
