### ISSUE TITLE
Crash in 0.31.0 in compactor: panic: cannot call histogramIterator.

### ISSUE THREAD

**Issue by JWThorne** [thanos-io/thanos#6983]
**Thanos, Prometheus and Golang version used**:
 thanos --version
thanos, version 0.32.0-dev (branch: main, revision: 6d838e7142d97cce81bcaada932992a4c40a5d80)
  build user:       root@buildkitsandbox
  build date:       20230421-19:15:42
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo

Prometheus: 
prometheus, version 2.41.0 (branch: HEAD, revision: c0d8a56c69014279464c0e15d8bfb0e153af0dab)
  build user:       root@d20a03e77067
  build date:       20221220-10:40:45
  go version:       go1.19.4
  platform:         linux/amd64

**Object Storage Provider**:
Filesystem

**What happened**:
Crash in compactor at the end of a downsample run. 

**What you expected to happen**:
No crash

**How to reproduce it (as minimally and precisely as possible)**:
run a downsample

**Full logs to relevant components**:

level=info ts=2023-12-15T19:37:19.907809472Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=11.963259ms duration_ms=11 cached=8 returned=8 partial=0
level=info ts=2023-12-15T19:37:20.186688717Z caller=streamed_block_writer.go:178 msg="finalized downsampled block" mint=1702425600000 maxt=1702598400000 ulid=01HHQFH4BT2G108491WMY9FV0J resolution=300000
panic: cannot call histogramIterator.At

goroutine 799 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.(*histogramIterator).At(0xc000ccdb80?)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.43.1-0.20230414053501-7309ac272195/tsdb/chunkenc/histogram.go:662 +0x27
github.com/thanos-io/thanos/pkg/compact/downsample.expandChunkIterator({0x2b7d690, 0xc000ccdb80}, 0xc0048ef7f8)
	/go/src/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go:473 +0x62
github.com/thanos-io/thanos/pkg/compact/downsample.Downsample({0x2b562a0, 0xc0008d2190}, 0xc0002450e0, {0x2b72da0, 0xc000ab5b80}, {0xc00050a880, 0x1e}, 0x493e0)
	/go/src/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go:153 +0x11b8
main.processDownsampling({0x2b6f060, 0xc000aebd60}, {0x2b562a0, 0xc0008d2190}, {0x2b83968, 0xc000a48c20}, 0xc0002450e0, {0xc00050a880, 0x1e}, 0x493e0, ...)
	/go/src/github.com/thanos-io/thanos/cmd/thanos/downsample.go:377 +0x707
main.downsampleBucket.func3()
	/go/src/github.com/thanos-io/thanos/cmd/thanos/downsample.go:258 +0x207
created by main.downsampleBucket
	/go/src/github.com/thanos-io/thanos/cmd/thanos/downsample.go:249 +0xa5c

**Anything else we need to know**:

**Comment by yeya24** [comment]
Downsample native histogram is not supported if I understand correctly. @rabenhorst

**Comment by JWThorne** [comment]
how do I disable it then?

**Comment by yeya24** [comment]
You have to upgrade your Thanos Compactor to latest main to include https://github.com/thanos-io/thanos/pull/6893 and upload a no downsample marker.

**Comment by JWThorne** [comment]
Oh. I'll have to switch to a minio bucket. We can't retain enough data without downsampling. Thanks for the update.

**Comment by rabenhorst** [comment]
> Downsample native histogram is not supported if I understand correctly. @rabenhorst @fpetkovski

That's right. There is a PR #6350, but it's not ready yet and we have to see if that is the right approach.

**Comment by LarsFronius** [comment]
We are seeing this crash after a couple of hours of ingesting data in the compactor in a setup where native histograms are not activated.
Here's the full configuration and crash log for reference:

Image: `thanosio/thanos:v0.36.1`
Command: `compact --log.level=info --log.format=logfmt --http-address=0.0.0.0:10902 --data-dir=/data --retention.resolution-raw=14d --retention.resolution-5m=30d --retention.resolution-1h=10y --consistency-delay=30m --objstore.config-file=/conf/objstore.yml --wait`
```
ts=2024-11-14T10:37:45.603451922Z caller=fetcher.go:623 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=395.67226ms duration_ms=395 cached=103 returned=8 partial=0
ts=2024-11-14T10:38:00.6246465Z caller=downsample.go:364 level=info msg="downloaded block" id=01JCMK7Y4QC0ABD0TTMC1HX87D duration=15.020585853s duration_ms=15020
ts=2024-11-14T10:38:25.539572628Z caller=streamed_block_writer.go:178 level=info msg="finalized downsampled block" mint=1730952873701 maxt=1731103200000 ulid=01JCN41EGW8N1PFB69ZNWZP20J resolution=300000
panic: cannot call histogramIterator.At

goroutine 1535 [running]:
github.com/prometheus/prometheus/tsdb/chunkenc.(*histogramIterator).At(0xc001662160?)
/go/pkg/mod/github.com/prometheus/prometheus@v0.52.2-0.20240614130246-4c1e71fa0b3d/tsdb/chunkenc/histogram.go:780 +0x25
github.com/thanos-io/thanos/pkg/compact/downsample.expandChunkIterator({0x38e7608, 0xc001662160}, 0xc0011e9380)
/app/pkg/compact/downsample/downsample.go:484 +0x5b
github.com/thanos-io/thanos/pkg/compact/downsample.Downsample({0x38db3b0, 0xc000da9e50}, {0x38b9f40, 0xc000ca1ac0}, 0xc0013b8b40, {0x38ddaf0, 0xc001662420}, {0xc000c115a0, 0x10}, 0x493e0)
/app/pkg/compact/downsample/downsample.go:155 +0x1154
main.processDownsampling({0x38db3b0, 0xc000da9e50}, {0x38b9f40, 0xc000ca1ac0}, {0x38f2518, 0xc0011256c0}, 0xc0013b8b40, {0xc000c115a0, 0x10}, 0x493e0, ...)
/app/cmd/thanos/downsample.go:385 +0x89e
main.downsampleBucket.func3()
/app/cmd/thanos/downsample.go:265 +0x21b
created by main.downsampleBucket in goroutine 202
/app/cmd/thanos/downsample.go:256 +0xa70
```

**Prometheus**
Image: `quay.io/prometheus/prometheus:v2.55.1`
Command: `--web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries --config.file=/etc/prometheus/config_out/prometheus.env.yaml --web.enable-lifecycle --web.enable-remote-write-receiver --web.external-url=http://prometheus.service.dev.internal.calida.digital/ --web.route-prefix=/ --storage.tsdb.retention.time=10d --storage.tsdb.path=/prometheus --storage.tsdb.wal-compression --web.config.file=/etc/prometheus/web_config/web-config.yaml --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h`

**Prometheus Thanos Sidecar**
Image: `thanosio/thanos:v0.36.1`
Command: `sidecar --prometheus.url=http://localhost:9090/ --grpc-address=:10901 --http-address=:10902 --objstore.config=$(OBJSTORE_CONFIG) --tsdb.path=/prometheus --log.level=info --log.format=logfmt --prometheus.http-client-file=/etc/thanos/config/prometheus.http-client-file.yaml`

Is this an incompatibility with recent versions of Prometheus, or is there something in our configuration that we need missed?

**Comment by LarsFronius** [comment]
This looks to be fixed in v0.38.0. Can you confirm @JWThorne ?
