### ISSUE TITLE
thanos compact panic on GetActiveAndPartialBlockIDs

### ISSUE THREAD

**Issue by jzelinskie** [thanos-io/thanos#7491]
**Thanos, Prometheus and Golang version used**:

```
thanos, version 0.35.0 (branch: HEAD, revision: d9a0efab5709ff6eccc37804996f29990e92ffa5)
  build user:       root@475652f059b4
  build date:       20240502-10:45:11
  go version:       go1.21.9
  platform:         linux/amd64
  tags:             netgo
```

**Object Storage Provider**: S3

**What happened**: It panicked with

```
panic: send on closed channel

goroutine 1416456275 [running]:
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func1()
	/app/pkg/block/fetcher.go:260 +0x20c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1416456228
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

**What you expected to happen**: No panic

**Full logs to relevant components**:

<details>Logs
<p>

```
will update with more info
```

</p>
</details>

**Environment**:
- OS (e.g. from /etc/os-release): official container
- Kernel (e.g. `uname -a`): `Linux thanos-compact-0 5.15.146+ #1 SMP Tue Apr 2 11:55:25 UTC 2024 x86_64 GNU/Linux`

**Comment by yeya24** [comment]
I think I hit exactly the same error when context was canceled.
I wonder if it helps to add a context check [here](https://github.com/thanos-io/thanos/blob/main/pkg/block/fetcher.go#L260) before sending id to the channel

**Comment by hgsat123** [comment]
Hi,
I'm seeing the same error both in Store & Compactor. I'm able to reproduce this error on latest thanos 0.36.0 (both store & compactor) as well 

-- On thanos store 
ts=2024-08-09T11:58:11.063840179Z caller=stdlib.go:105 level=debug s3TraceMsg=---------END-HTTP---------

panic: send on closed channel

goroutine 126555170 [running]:
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func1()
	/app/pkg/block/fetcher.go:260 +0x20c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 126555148
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96


On Thanos compactor 
===================
caller=runutil.go:117 level=error msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: read tcp 100.xx:xxx:xxx:32932->10.xx.xxx.xxxx:80 read: connection reset by peer"
panic: send on closed channel

goroutine 178914629 [running]:
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func1()
	/app/pkg/block/fetcher.go:260 +0x20c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 178914622
	/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96

This issue has to be fixed as its been in around for a while. store & compactor pods have restart in production due to this panic!!

**Comment by yeya24** [comment]
Hi @hgsat123 @jzelinskie, can you please help test setting `--block-discovery-strategy=recursive`. Is this problem still reproducible?

**Comment by hgsat123** [comment]
> Hi @hgsat123 @jzelinskie, can you please help test setting `--block-discovery-strategy=recursive`. Is this problem still reproducible?

Sure. Let me test. As i mentioned i've seen / reproducible issue on 0.35.0, 0.35.1 & even in the latest 0.36.0 thanos release. Issue is reproducible only in Compactor & store (statefulset) instances

**Comment by sjentzsch** [comment]
Running Thanos v0.37.2 we still see the issue occur quite frequently in our thanos-storegateway pods:

```
panic: send on closed channel

goroutine 518008 [running]:
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func1()
    /bitnami/blacksmith-sandox/thanos-0.37.2/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:260 +0x29c
golang.org/x/sync/errgroup.(*Group).Go.func1()
    /bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 518003
    /bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```

**Comment by janisii** [comment]
We are also seeing this on Thanos v0.37.2 compactor pod.

`docker.io/bitnami/thanos:0.37.2-debian-12-r9`

```
2025-07-16 02:46:06.910 ts=2025-07-15T23:46:06.910543011Z caller=fetcher.go:627 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.658915204s duration_ms=1658 cached=9475 returned=9475 partial=0
2025-07-16 02:47:05.500	panic: send on closed channel
2025-07-16 02:47:05.500	
2025-07-16 02:47:05.500	goroutine 14828873 [running]:
2025-07-16 02:47:05.500	github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func1()
2025-07-16 02:47:05.500		/bitnami/blacksmith-sandox/thanos-0.37.2/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:260 +0x29c
2025-07-16 02:47:05.500	golang.org/x/sync/errgroup.(*Group).Go.func1()
2025-07-16 02:47:05.500		/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
2025-07-16 02:47:05.500	created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 14828846
2025-07-16 02:47:05.501		/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
2025-07-16 02:47:06.255	ts=2025-07-15T23:47:06.255700669Z caller=factory.go:54 level=info msg="loading bucket configuration"
```

**Comment by LijieZhou-inworld** [comment]
We are seeing the same issue on Thanos v0.37.2 store-gateway pod. 

```
grep -A20 "goroutine 4173555" /tmp/goroutine-dump-0-1.txt
goroutine 4173555 [select, 1967 minutes]:
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs.func2({0xc0384c1a40?, 0xc01198a700?})
	/bitnami/blacksmith-sandox/thanos-0.37.2/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:275 +0xcc
github.com/thanos-io/objstore/providers/oci.(*Bucket).Iter(0xc000189c20, {0x39d9eb0?, 0xc0012079f0?}, {0x0?, 0x0?}, 0xc02584cf60, {0x0?, 0x0?, 0x0?})
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20241111205755-d1dd89d41f97/providers/oci/oci.go:129 +0x417
github.com/thanos-io/objstore.(*metricBucket).Iter(0xc0001c9a70, {0x39d9eb0, 0xc0012079f0}, {0x0, 0x0}, 0xc02584cf60, {0x0, 0x0, 0x0})
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20241111205755-d1dd89d41f97/objstore.go:612 +0x1e4
github.com/thanos-io/objstore/tracing/opentracing.(*TracingBucket).Iter.TracingBucket.Iter.func1({0x39d9eb0, 0xc0012079f0}, {0x39f7440, 0x50fe7c0})
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20241111205755-d1dd89d41f97/tracing/opentracing/opentracing.go:50 +0x158
github.com/thanos-io/objstore/tracing/opentracing.doWithSpan({0x39d9eb0?, 0xc0012079f0?}, {0x2ba7a36?, 0x7fa6ad6a9790?}, 0xc009926e18, {0x0?, 0x7fa6f47465b8?, 0x20?})
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20241111205755-d1dd89d41f97/tracing/opentracing/opentracing.go:227 +0x8c
github.com/thanos-io/objstore/tracing/opentracing.TracingBucket.Iter(...)
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20241111205755-d1dd89d41f97/tracing/opentracing/opentracing.go:48
github.com/thanos-io/thanos/pkg/block.(*ConcurrentLister).GetActiveAndPartialBlockIDs(0xc001204ba0, {0x39d9eb0, 0xc0012079f0}, 0xc038372a00)
	/bitnami/blacksmith-sandox/thanos-0.37.2/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:270 +0x258
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata.func2()
	/bitnami/blacksmith-sandox/thanos-0.37.2/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:521 +0x74
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 260
	/bitnami/blacksmith-sandox/thanos-0.37.2/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```
