### ISSUE TITLE
`thanos tools bucket rewrite` fails with a segmentation violation on v0.36.0 and later of thanos.

### ISSUE THREAD

**Issue by chris-barbour-as** [thanos-io/thanos#7844]
**Thanos, Prometheus and Golang version used**:

Thanos@0.36.1
Go@1.21

Also tested with:
thanos@main (v0.35.2-0.20241017120053-731e4607d34a according to go.mod)
go@1.23.2

Confirmed issue does not affect:
thanos@v0.35.1

**Object Storage Provider**:

FILESYSTEM

**What happened**:

Starting with v0.36.0 `thanos tools bucket rewrite` fails with a Segmentation Violation while attempting to write the new block back to the store.

**What you expected to happen**:

`thanos tools bucket rewrite` should not fail with a Segmentation Violation

**How to reproduce it (as minimally and precisely as possible)**:

Attached go code will reproduce error.

My specific command invocation is as follows:

`thanos tools bucket rewrite --objstore.config-file=objstore-local.yaml --rewrite.to-relabel-config-file=relabel-config.yaml --no-dry-run --delete-blocks --id "01HCGZPEM6EEHJ75218N914HNM" --tmp.dir="/home/appuser/data/thanos-rewrite"`

objstore-local.yaml:

```
type: FILESYSTEM
config:
  directory: "/home/appuser/data"
prefix: ""
```

relabel-config.yaml:
```
- action: replace
  target_label: "foo"
  replacement: "bar"
```

However, the attached code will reproduce the issue by simply running:

`go get`

`go run main.go`

**Full logs to relevant components**:

<details>Logs
<p>

```
Start time: Sat Oct 19 01:43:15 UTC 2024
ts=2024-10-19T01:43:15.39052425Z caller=factory.go:53 level=info msg="loading bucket configuration"
ts=2024-10-19T01:43:15.406953575Z caller=fetcher.go:623 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=16.053695ms duration_ms=16 cached=1077 returned=1077 partial=0
ts=2024-10-19T01:43:15.414714245Z caller=main.go:174 level=info msg=exiting
ts=2024-10-19T01:43:15.44098453Z caller=factory.go:53 level=info msg="loading bucket configuration"
ts=2024-10-19T01:43:17.14659156Z caller=tools_bucket.go:1226 level=info msg="downloading block" source=01HCGZPEM6EEHJ75218N914HNM
ts=2024-10-19T01:46:02.077523638Z caller=tools_bucket.go:1263 level=info msg="changelog will be available" file=/home/appuser/data/thanos-rewrite/01JAH77XYXDS8NBHFBJFKCS3V1/change.log
ts=2024-10-19T01:46:02.134607708Z caller=tools_bucket.go:1278 level=info msg="starting rewrite for block" source=01HCGZPEM6EEHJ75218N914HNM new=01JAH77XYXDS8NBHFBJFKCS3V1 toDelete= toRelabel="- action: replace\n  target_label: \"foo\"\n  replacement: \"bar\"\n- action: replace\n"
ts=2024-10-19T01:49:15.763983386Z caller=compactor.go:42 level=info msg="processed 10.00% of 3419617 series"
ts=2024-10-19T01:49:47.464508668Z caller=compactor.go:42 level=info msg="processed 20.00% of 3419617 series"
ts=2024-10-19T01:50:48.513697195Z caller=compactor.go:42 level=info msg="processed 30.00% of 3419617 series"
ts=2024-10-19T01:51:20.873113385Z caller=compactor.go:42 level=info msg="processed 40.00% of 3419617 series"
ts=2024-10-19T01:51:25.882289646Z caller=compactor.go:42 level=info msg="processed 50.00% of 3419617 series"
ts=2024-10-19T01:51:37.924141467Z caller=compactor.go:42 level=info msg="processed 60.00% of 3419617 series"
ts=2024-10-19T01:51:43.005992941Z caller=compactor.go:42 level=info msg="processed 70.00% of 3419617 series"
ts=2024-10-19T01:55:21.447415738Z caller=compactor.go:42 level=info msg="processed 80.00% of 3419617 series"
ts=2024-10-19T01:56:18.949121034Z caller=compactor.go:42 level=info msg="processed 90.00% of 3419617 series"
ts=2024-10-19T01:57:32.258928562Z caller=compactor.go:42 level=info msg="processed 100.00% of 3419617 series"
ts=2024-10-19T01:57:32.26977951Z caller=tools_bucket.go:1288 level=info msg="wrote new block after modifications; flushing" source=01HCGZPEM6EEHJ75218N914HNM new=01JAH77XYXDS8NBHFBJFKCS3V1
ts=2024-10-19T01:58:03.092458808Z caller=tools_bucket.go:1297 level=info msg="uploading new block" source=01HCGZPEM6EEHJ75218N914HNM new=01JAH77XYXDS8NBHFBJFKCS3V1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92573b]

goroutine 102 [running]:
github.com/grafana/regexp.(*Regexp).UnmarshalText(0x0, {0xc129d88463?, 0xc0f46c6f08?, 0x2907820?})
	/go/pkg/mod/github.com/grafana/regexp@v0.0.0-20240518133315-a468a5bfb3bc/regexp.go:1302 +0x3b
encoding/json.(*decodeState).literalStore(0xc0005b4b68, {0xc129d88462, 0xc, 0x199e}, {0x2907820?, 0xc0f46c6f08?, 0x27ddc00?}, 0x0)
	/usr/local/go/src/encoding/json/decode.go:877 +0x5f3
encoding/json.(*decodeState).value(0xc0005b4b68, {0x2907820?, 0xc0f46c6f08?, 0x5?})
	/usr/local/go/src/encoding/json/decode.go:388 +0x115
encoding/json.(*decodeState).object(0xc0005b4b68, {0x24d0120?, 0xc0001de298?, 0x23212c0?})
	/usr/local/go/src/encoding/json/decode.go:755 +0xd08
encoding/json.(*decodeState).value(0xc0005b4b68, {0x24d0120?, 0xc0001de298?, 0x1?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).array(0xc0005b4b68, {0x23212c0?, 0xc0f3ef2710?, 0x313c?})
	/usr/local/go/src/encoding/json/decode.go:555 +0x50f
encoding/json.(*decodeState).value(0xc0005b4b68, {0x23212c0?, 0xc0f3ef2710?, 0x10?})
	/usr/local/go/src/encoding/json/decode.go:364 +0x74
encoding/json.(*decodeState).object(0xc0005b4b68, {0x2629080?, 0xc0f3ef26e0?, 0x2325400?})
	/usr/local/go/src/encoding/json/decode.go:755 +0xd08
encoding/json.(*decodeState).value(0xc0005b4b68, {0x2629080?, 0xc0f3ef26e0?, 0x1?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).array(0xc0005b4b68, {0x2325400?, 0xc0005b4b00?, 0x38c3?})
	/usr/local/go/src/encoding/json/decode.go:555 +0x50f
encoding/json.(*decodeState).value(0xc0005b4b68, {0x2325400?, 0xc0005b4b00?, 0x8?})
	/usr/local/go/src/encoding/json/decode.go:364 +0x74
encoding/json.(*decodeState).object(0xc0005b4b68, {0x282b140?, 0xc0005b4aa8?, 0x39c0?})
	/usr/local/go/src/encoding/json/decode.go:755 +0xd08
encoding/json.(*decodeState).value(0xc0005b4b68, {0x282b140?, 0xc0005b4aa8?, 0x6?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).object(0xc0005b4b68, {0x252fa40?, 0xc0005b4a00?, 0xc0005f8ee8?})
	/usr/local/go/src/encoding/json/decode.go:755 +0xd08
encoding/json.(*decodeState).value(0xc0005b4b68, {0x252fa40?, 0xc0005b4a00?, 0xc0005f8f38?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc0005b4b68, {0x252fa40?, 0xc0005b4a00?})
	/usr/local/go/src/encoding/json/decode.go:181 +0x133
encoding/json.(*Decoder).Decode(0xc0005b4b40, {0x252fa40, 0xc0005b4a00})
	/usr/local/go/src/encoding/json/stream.go:73 +0x179
github.com/thanos-io/thanos/pkg/block/metadata.Read({0x38c90e8?, 0xc0001de288})
	/app/pkg/block/metadata/meta.go:260 +0x10c
github.com/thanos-io/thanos/pkg/block/metadata.ReadFromDir({0xc11dc14680, 0x3c})
	/app/pkg/block/metadata/meta.go:252 +0x8e
github.com/thanos-io/thanos/pkg/block.upload({0x38db3b0, 0xc0000ce550}, {0x38b9f40, 0xc0001c4440}, {0x38f2518?, 0xc000622820?}, {0xc11dc14680, 0x3c}, {0x0, 0x0}, ...)
	/app/pkg/block/block.go:126 +0x125
github.com/thanos-io/thanos/pkg/block.Upload(...)
	/app/pkg/block/block.go:98
main.registerBucketRewrite.func1.1()
	/app/cmd/thanos/tools_bucket.go:1303 +0x1cf6
github.com/oklog/run.(*Group).Run.func1({0xc000a5eb60?, 0xc000622ad0?})
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x67
```

</p>
</details>

**Anything else we need to know**:

The issue is specifically related to the helpful information that `thanos tools bucket rewrite` adds to the updated block's meta.json file.

The following JSON can be used to reproduce the problem:

```
{
  "thanos": {
    "rewrites": [
      {
        "relabels_applied": [
          {
            "SourceLabels": null,
            "Separator": ";",
            "Regex": "foo",
            "Modulus": 0,
            "TargetLabel": "bar",
            "Replacement": "baz",
            "Action": "replace"
          }
        ]
      }
    ]
  }
}
```

Removing `"Regex": "foo",` will make the problem go away. See attached code.

[thanos-rewrites-segv.tar.gz](https://github.com/user-attachments/files/17442713/thanos-rewrites-segv.tar.gz)

**Comment by chris-barbour-as** [comment]
Possible this is related to: https://github.com/thanos-io/thanos/pull/7338

**Comment by yeya24** [comment]
@chris-barbour-as The issue here is that `relabel.Regexp` doesn't implement json encoder/decoder like it does for YAML hence it doesn't handle the regexp pointer correctly.

We can either change Prometheus or switch to use jsoniter in Thanos so that we can add our own encoding/decoding function to `relabel.Regexp`

**Comment by yeya24** [comment]
I created https://github.com/prometheus/prometheus/pull/15383 which should fix this issue.

**Comment by rafaelpirolla** [comment]
Just tried within a docker-compose environment with this yml:
```yml
- action: replace
  source_labels: [host]
  target_label: host
  replacement: abc
  regex: hostname
```
And produced this using minio:
    image: minio/minio:latest
Would be version 2024-11-21T17-21-54Z.

Gave me this error:
```
ts=2025-01-08T15:49:05.456707049Z caller=tools_bucket.go:1298 level=info msg="uploading new block" source=01JH397E61TK0GEM2SQEQAC4S0 new=01JH39NTQWWXN8TK397XJTKHXC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98d6fb]

goroutine 114 [running]:
github.com/grafana/regexp.(*Regexp).UnmarshalText(0x0, {0xc0005b2335?, 0x2b6d800?, 0xc000db9f38?})
        /go/pkg/mod/github.com/grafana/regexp@v0.0.0-20240518133315-a468a5bfb3bc/regexp.go:1302 +0x3b
encoding/json.(*decodeState).literalStore(0xc0001ba7a8, {0xc0005b2334, 0x10, 0x2cc}, {0x2b6d800?, 0xc000db9f38?, 0xc000db9f10?}, 0x0)
        /usr/local/go/src/encoding/json/decode.go:879 +0x5e2
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x2b6d800?, 0xc000db9f38?, 0x5?})
        /usr/local/go/src/encoding/json/decode.go:388 +0x115
encoding/json.(*decodeState).object(0xc0001ba7a8, {0x26f2940?, 0xc000088738?, 0x2526b80?})
        /usr/local/go/src/encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x26f2940?, 0xc000088738?, 0x1?})
        /usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).array(0xc0001ba7a8, {0x2526b80?, 0xc0000ffde0?, 0x199?})
        /usr/local/go/src/encoding/json/decode.go:555 +0x50f
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x2526b80?, 0xc0000ffde0?, 0x10?})
        /usr/local/go/src/encoding/json/decode.go:364 +0x74
encoding/json.(*decodeState).object(0xc0001ba7a8, {0x2860180?, 0xc0000ffdb0?, 0x252b9c0?})
        /usr/local/go/src/encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x2860180?, 0xc0000ffdb0?, 0x1?})
        /usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).array(0xc0001ba7a8, {0x252b9c0?, 0xc0001ba740?, 0x481?})
        /usr/local/go/src/encoding/json/decode.go:555 +0x50f
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x252b9c0?, 0xc0001ba740?, 0x8?})
        /usr/local/go/src/encoding/json/decode.go:364 +0x74
encoding/json.(*decodeState).object(0xc0001ba7a8, {0x2a7e3e0?, 0xc0001ba6e8?, 0x4f2?})
        /usr/local/go/src/encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x2a7e3e0?, 0xc0001ba6e8?, 0x6?})
        /usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).object(0xc0001ba7a8, {0x2757b80?, 0xc0001ba640?, 0xc0005df030?})
        /usr/local/go/src/encoding/json/decode.go:755 +0xd11
encoding/json.(*decodeState).value(0xc0001ba7a8, {0x2757b80?, 0xc0001ba640?, 0xc0005df080?})
        /usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc0001ba7a8, {0x2757b80?, 0xc0001ba640?})
        /usr/local/go/src/encoding/json/decode.go:181 +0x11e
encoding/json.(*Decoder).Decode(0xc0001ba780, {0x2757b80, 0xc0001ba640})
        /usr/local/go/src/encoding/json/stream.go:73 +0x15a
github.com/thanos-io/thanos/pkg/block/metadata.Read({0x39c6658, 0xc000088728})
        /app/pkg/block/metadata/meta.go:260 +0x10a
github.com/thanos-io/thanos/pkg/block/metadata.ReadFromDir({0xc00098aa20, 0x2e})
        /app/pkg/block/metadata/meta.go:252 +0x8e
github.com/thanos-io/thanos/pkg/block.upload({0x39d9f50, 0xc000630c30}, {0x39b66e0, 0xc000981640}, {0x39f7ae0, 0xc000cbef40}, {0xc00098aa20, 0x2e}, {0x0, 0x0}, ...)
        /app/pkg/block/block.go:126 +0x10a
github.com/thanos-io/thanos/pkg/block.Upload(...)
        /app/pkg/block/block.go:98
main.registerBucketRewrite.func1.1()
        /app/cmd/thanos/tools_bucket.go:1304 +0x1c25
github.com/oklog/run.(*Group).Run.func1({0xc000b0d790?, 0xc000cbf120?})
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x5a
```

**Comment by rafaelpirolla** [comment]
Hi @yeya24, do you think this is related to the issue?
